---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: tautulli-config
  labels:
    k8s-app: tautulli

spec:
  accessModes:
  - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
