---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: soju-data
  labels:
    velero.io/backup: 'true'

spec:
  storageClassName: synology-iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
