---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: bambuddy-secrets
  namespace: bambuddy

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: bambuddy-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        MFA_ENCRYPTION_KEY: "{{ .mfa_encryption_key }}"
        JWT_SECRET_KEY: "{{ .jwt_secret_key }}"
  data:
  - secretKey: mfa_encryption_key
    remoteRef:
      key: bambuddy
      property: mfa-encryption-key
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: jwt_secret_key
    sourceRef:
      generatorRef:
        kind: Password
        name: bambuddy-jwt

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: bambuddy-postgres-app
  namespace: bambuddy

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: bambuddy-postgres-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: bambuddy
        password: "{{ .db_password }}"
        DATABASE_URL: "postgresql+asyncpg://bambuddy:{{ .db_password }}@bambuddy-postgres-rw:5432/bambuddy"
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: db_password
    sourceRef:
      generatorRef:
        kind: Password
        name: bambuddy-postgres
