---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: external-dns

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: external-dns-cloudflare-creds
  data:
  - secretKey: CF_API_TOKEN
    remoteRef:
      key: cloudflare-dns-write
      property: CF_Token
