---
provider:
  name: cloudflare

policy: sync
registry: noop
triggerLoopOnEvent: true
domainFilters:
- k.oneill.net
extraArgs:
- --zone-id-filter=5a8d9de1c40f089d2f98f49a4569e1cd
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: external-dns-cloudflare-creds
      key: CF_API_TOKEN
