---
provider:
  name: cloudflare

policy: sync
txtPrefix: extdns-
txtOwnerId: external-dns
triggerLoopOnEvent: true
domainFilters:
- oneill.net
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: external-dns-cloudflare-creds
      key: CF_API_TOKEN
