---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: grimmory
  namespace: grimmory

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grimmory
  template:
    metadata:
      labels:
        app: grimmory
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: grimmory
        image: grimmory/grimmory:v3.2.2@sha256:c3fc5ed1d30e33fb6c276dfbb438d29eb7b8f082a6b0c8a66d285564ee758246
        ports:
        - containerPort: 6060
          name: http
        env:
        - name: BOOKLORE_PORT
          value: '6060'
        - name: DATABASE_URL
          value: jdbc:mariadb://grimmory-mariadb.grimmory.svc.cluster.local:3306/grimmory?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
        - name: DATABASE_USERNAME
          value: grimmory
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grimmory-mariadb-secrets
              key: user-password
        - name: TZ
          value: EST5EDT
        - name: USER_ID
          value: '10001'
        - name: GROUP_ID
          value: '10001'
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: books
          mountPath: /books
        - name: bookdrop
          mountPath: /bookdrop
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grimmory-data
      - name: books
        nfs:
          server: fs2.oneill.net
          path: /volume2/shared/books/grimmory
      - name: bookdrop
        nfs:
          server: fs2.oneill.net
          path: /volume2/shared/downloads/grimmory-ingestion
