---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: grimmory-mariadb-secrets
  namespace: grimmory

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: grimmory-mariadb-secrets
    creationPolicy: Owner
  data:
  - secretKey: root-password
    remoteRef:
      key: grimmory-mariadb
      property: root-password
  - secretKey: user-password
    remoteRef:
      key: grimmory-mariadb
      property: user-password
