---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grimmory-mariadb-data
  namespace: grimmory

spec:
  accessModes:
  - ReadWriteOncePod
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
