---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: grimmory-mariadb
  namespace: grimmory

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grimmory-mariadb
  template:
    metadata:
      labels:
        app: grimmory-mariadb
    spec:
      containers:
      - name: grimmory-mariadb
        image: mariadb:11.8@sha256:2439dcd7d14010ecd1ff7a4e1c5abe8e208c34fe35290744deeeaac3569043c3
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MARIADB_AUTO_UPGRADE
          value: '1'
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grimmory-mariadb-secrets
              key: root-password
        - name: MARIADB_DATABASE
          value: grimmory
        - name: MARIADB_USER
          value: grimmory
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grimmory-mariadb-secrets
              key: user-password
        readinessProbe:
          exec:
            command:
            - healthcheck.sh
            - --connect
            - --innodb_initialized
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grimmory-mariadb-data
