---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: rclone-exporter

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_URL
    remoteRef:
      key: hetzner-restic-main
      property: url
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_USER
    remoteRef:
      key: hetzner-restic-main
      property: username
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_PASS
    remoteRef:
      key: hetzner-restic-rclone
      property: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_PASS
  - secretKey: RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_MAIN_PASSWORD
    remoteRef:
      key: hetzner-restic-main
      property: RCLONE_CONFIG_HETZNER_RESTIC_PASSWORD
  - secretKey: RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_MAIN_PASSWORD2
    remoteRef:
      key: hetzner-restic-main
      property: RCLONE_CONFIG_HETZNER_RESTIC_PASSWORD2
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_URL
    remoteRef:
      key: hetzner-restic-xtal
      property: url
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_USER
    remoteRef:
      key: hetzner-restic-xtal
      property: username
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_PASS
    remoteRef:
      key: hetzner-restic-rclone
      property: RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_PASS
  - secretKey: RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_XTAL_PASSWORD
    remoteRef:
      key: hetzner-restic-xtal
      property: RCLONE_CONFIG_HETZNER_RESTIC_PASSWORD
  - secretKey: RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_XTAL_PASSWORD2
    remoteRef:
      key: hetzner-restic-xtal
      property: RCLONE_CONFIG_HETZNER_RESTIC_PASSWORD2
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_VELERO_URL
    remoteRef:
      key: hetzner-velero
      property: url
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_VELERO_USER
    remoteRef:
      key: hetzner-velero
      property: username
  - secretKey: RCLONE_CONFIG_HETZNER_WEBDAV_VELERO_PASS
    remoteRef:
      key: hetzner-velero-rclone
      property: RCLONE_CONFIG_HETZNER_WEBDAV_VELERO_PASS
  - secretKey: RCLONE_CONFIG_HETZNER_VELERO_PASSWORD
    remoteRef:
      key: hetzner-velero-rclone
      property: RCLONE_CONFIG_HETZNER_VELERO_PASSWORD
  target:
    name: rclone-exporter
