[hetzner_webdav_restic_main]
type = webdav
vendor = other

[hetzner_webdav_restic_xtal]
type = webdav
vendor = other

[hetzner_webdav_velero]
type = webdav
vendor = other

[hetzner_crypt_restic_main]
type = crypt
remote = hetzner_webdav_restic_main:
filename_encryption = standard
directory_name_encryption = true

[hetzner_crypt_restic_xtal]
type = crypt
remote = hetzner_webdav_restic_xtal:
filename_encryption = standard
directory_name_encryption = true

[hetzner_velero]
type = crypt
remote = hetzner_webdav_velero:
filename_encryption = standard
directory_name_encryption = true
