---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: seerr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: seerr
      app.kubernetes.io/name: seerr
      app.kubernetes.io/instance: seerr
  template:
    metadata:
      labels:
        app: seerr
        app.kubernetes.io/name: seerr
        app.kubernetes.io/instance: seerr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: seerr
        image: ghcr.io/seerr-team/seerr:v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
        ports:
        - containerPort: 5055
        volumeMounts:
        - mountPath: /app/config
          name: config
        env:
        - name: TZ
          value: EST5EDT
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: seerr-config
