---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: authentik-postgres

spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie@sha256:81bad466fe006454482678c6c67a24c1e30454b519011e0196cba2e4c83e1e1a
  enablePDB: true

  storage:
    size: 10Gi

  postgresql:
    parameters:
      max_connections: '200'

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
