---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: homebox-api-key-pepper

spec:
  length: 64
  digits: 16
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
  - HBOX_AUTH_API_KEY_PEPPER

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: homebox-api-key-pepper

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: homebox-api-key-pepper
  target:
    name: homebox-api-key-pepper
