---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: homebox-oidc

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: HBOX_OIDC_CLIENT_ID
    remoteRef:
      key: homebox-oidc
      property: client-id
  - secretKey: HBOX_OIDC_CLIENT_SECRET
    remoteRef:
      key: homebox-oidc
      property: client-secret
  target:
    name: homebox-oidc
