---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:

- homebox-postgres-cluster.yaml
- externalsecret-oidc.yaml

  # HomeBox resources
- helm/homebox/deployment.yaml
- helm/homebox/secrets.yaml
- helm/homebox/service.yaml
- helm/homebox/pvc.yaml
- helm/homebox/serviceaccount.yaml
- helm/homebox/ingress.yaml

commonAnnotations:
  argoManaged: 'true'

images:
- name: sysadminsmedia/homebox
  newTag: 0.25.0@sha256:6506480a3dfadd2cc885fa97b32d11b0ee28ec58629fa34a76afdb4ac540c7fc

patches:

- target:
    kind: Deployment
    name: homebox
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: homebox
    spec:
      template:
        spec:
          containers:
          - name: homebox
            env:
            - name: HBOX_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homebox-postgres-app
                  key: password
            - name: HBOX_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: homebox-oidc
                  key: HBOX_OIDC_CLIENT_ID
            - name: HBOX_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: homebox-oidc
                  key: HBOX_OIDC_CLIENT_SECRET

# Add labels for metrics
labels:

- pairs:
    app.kubernetes.io/name: homebox
    app.kubernetes.io/instance: homebox
