---
apiVersion: batch/v1
kind: CronJob

metadata:
  name: got-your-back-full

spec:
  schedule: 18 9 * * 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: got-your-back
            image: debian:stable-slim@sha256:ee12ffb55625b99d62837a72f037d9b2f18fd0c787a89c2b9a4f09666c48776c
            command: [/usr/local/bin/run]
            imagePullPolicy: Always
            env:
            - name: HEALTHCHECK_PING_KEY
              valueFrom:
                secretKeyRef:
                  name: healthchecks
                  key: HEALTHCHECK_PING_KEY
            - name: CHECK_NAME
              value: got-your-back-full
            volumeMounts:
            - name: config
              mountPath: /config
            - name: config-source
              mountPath: /config-source
            - name: run-script
              mountPath: /usr/local/bin/run
              subPath: run
            - name: got-your-back-data
              mountPath: /data
          volumes:
          - name: config
            emptyDir: {}
          - name: config-source
            secret:
              secretName: got-your-back
          - name: run-script
            configMap:
              name: run-script
              defaultMode: 0755
          - name: got-your-back-data
            persistentVolumeClaim:
              claimName: got-your-back-data
          restartPolicy: OnFailure
