---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: hass-postgres

spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:ebf3919504d7523a63e8e2fee9b051211de714644b36469275558c624afd50ec
  enablePDB: true

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: hass
      owner: hass
      encoding: UTF8
