---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hass

resources:
- namespace.yaml
- hass-postgres-cluster.yaml
- hass-externalsecrets.yaml
- helm/serviceaccount.yaml
- helm/service.yaml
- helm/statefulset.yaml
- helm/ingress.yaml
- config

images:
- name: ghcr.io/home-assistant/home-assistant
  newName: homeassistant/home-assistant
  newTag: 2026.6.4@sha256:adb3341e31e03e0048e60d8c1cf952e118a381ae258bb921d3da12a3b27bf0c2

labels:

- pairs:
    app.kubernetes.io/name: hass
    app.kubernetes.io/instance: hass
  includeSelectors: true
