---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hass

resources:
- namespace.yaml
- hass-postgres-cluster.yaml
- hass-externalsecrets.yaml
- helm/serviceaccount.yaml
- helm/service.yaml
- helm/statefulset.yaml
- helm/ingress.yaml
- config

images:
- name: ghcr.io/home-assistant/home-assistant
  newName: homeassistant/home-assistant
  newTag: 2026.4.4@sha256:c1e5f0147f4cb51ccb05bb30b62a1269cc1bd48a6274792d3b38a77ab274dfd2

labels:

- pairs:
    app.kubernetes.io/name: hass
    app.kubernetes.io/instance: hass
  includeSelectors: true
