---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hass

resources:
- namespace.yaml
- hass-postgres-cluster.yaml
- hass-externalsecrets.yaml
- helm/serviceaccount.yaml
- helm/service.yaml
- helm/statefulset.yaml
- helm/ingress.yaml
- config

images:
- name: ghcr.io/home-assistant/home-assistant
  newTag: 2026.2.3@sha256:96fa92d83fa8dae987fbbbcf58b1fea1140985ff6a8517b37f7b65c76ef20133

labels:

- pairs:
    app.kubernetes.io/name: hass
    app.kubernetes.io/instance: hass
  includeSelectors: true
