#!/usr/bin/env bash

set -eu -o pipefail

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$BASEDIR"

source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir -p tmp helm

# Render home-assistant chart
helm_template hass home-assistant --namespace hass --values values.yaml --output-dir tmp

# Move templates directly to helm/
mv tmp/home-assistant/templates/* helm/

# Remove test manifests
rm -rf helm/tests

# Clean up
rm -rf tmp
