---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: app-secrets
  namespace: hortusfox

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: admin-password
    sourceRef:
      generatorRef:
        kind: Password
        name: hortusfox-admin
  - rewrite:
    - regexp:
        source: password
        target: cronpw
    sourceRef:
      generatorRef:
        kind: Password
        name: hortusfox-cronpw

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: smtp-secrets
  namespace: hortusfox

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: smtp-secrets
    creationPolicy: Owner
  data:
  - secretKey: smtp-password
    remoteRef:
      key: smtp-relay
      property: relay-password
