---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: mariadb-secrets
  namespace: hortusfox

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: mariadb-secrets
    creationPolicy: Owner
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: root-password
    sourceRef:
      generatorRef:
        kind: Password
        name: hortusfox-mariadb-root
  - rewrite:
    - regexp:
        source: password
        target: user-password
    sourceRef:
      generatorRef:
        kind: Password
        name: hortusfox-mariadb-user
