---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: hortusfox-mariadb-root
  namespace: hortusfox

spec:
  length: 32
  allowRepeat: true
  noUpper: false
  digits: 8
  symbols: 0

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: hortusfox-mariadb-user
  namespace: hortusfox

spec:
  length: 32
  allowRepeat: true
  noUpper: false
  digits: 8
  symbols: 0

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: hortusfox-admin
  namespace: hortusfox

spec:
  length: 32
  allowRepeat: true
  noUpper: false
  digits: 8
  symbols: 0

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password

metadata:
  name: hortusfox-cronpw
  namespace: hortusfox

spec:
  length: 32
  allowRepeat: true
  noUpper: false
  digits: 8
  symbols: 0
