###############################################
# Auto-generated by ak-tool for grimmory OIDC 1Password item
###############################################

resource "random_password" "grimmory_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  grimmory_oidc_client_id = "grimmory"
  grimmory_oidc_secret    = random_password.grimmory_oidc.result
}

resource "onepassword_item" "grimmory_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "grimmory-oidc"
  category = "login"

  note_value = "OIDC client for grimmory. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.grimmory_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.grimmory_oidc_secret
    }
  }
}
