###############################################
# Auto-generated by ak-tool for homebox OIDC 1Password item
###############################################

resource "random_password" "homebox_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  homebox_oidc_client_id = "homebox"
  homebox_oidc_secret    = random_password.homebox_oidc.result
}

resource "onepassword_item" "homebox_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "homebox-oidc"
  category = "login"

  note_value = "OIDC client for homebox. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.homebox_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.homebox_oidc_secret
    }
  }
}
