###############################################
# Auto-generated by ak-tool for radarr (proxy)
###############################################

resource "authentik_provider_proxy" "radarr" {
  name                  = "radarr"
  external_host         = "https://radarr.k.oneill.net"
  internal_host         = "http://radarr.default.svc.cluster.local:7878"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://radarr.k.oneill.net/api(/|$)
  EOT
}

resource "authentik_application" "radarr" {
  name              = "radarr"
  slug              = "radarr"
  protocol_provider = authentik_provider_proxy.radarr.id
}
