###############################################
# Auto-generated by ak-tool for cwa-cwa (proxy)
###############################################

resource "authentik_provider_proxy" "cwa-cwa" {
  name                  = "cwa-cwa"
  external_host         = "https://cwa.k.oneill.net"
  internal_host         = "http://cwa.default.svc.cluster.local:8083"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


  skip_path_regex = <<-EOT
^https://cwa.k.oneill.net/opds.*
  EOT
}

resource "authentik_application" "cwa-cwa" {
  name              = "cwa-cwa"
  slug              = "cwa-cwa"
  protocol_provider = authentik_provider_proxy.cwa-cwa.id
}
