###############################################
# Auto-generated by ak-tool for pinepods (OIDC)
###############################################

resource "authentik_provider_oauth2" "pinepods" {
  name               = "pinepods"
  client_id          = local.pinepods_oidc_client_id
  client_secret      = local.pinepods_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://pinepods.k.oneill.net/api/auth/callback", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "pinepods" {
  name              = "pinepods"
  slug              = "pinepods"
  protocol_provider = authentik_provider_oauth2.pinepods.id
}
