###############################################
# Auto-generated by ak-tool for healthchecks (proxy)
###############################################

resource "authentik_provider_proxy" "healthchecks" {
  name                  = "healthchecks"
  external_host         = "https://hc.k.oneill.net"
  internal_host         = "http://healthchecks.healthchecks.svc.cluster.local:8000"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


  skip_path_regex = <<-EOT
^https://hc.k.oneill.net/api
^https://hc.k.oneill.net/ping
  EOT
}

resource "authentik_application" "healthchecks" {
  name              = "healthchecks"
  slug              = "healthchecks"
  protocol_provider = authentik_provider_proxy.healthchecks.id
}
