###############################################
# Auto-generated by ak-tool for prowlarr (proxy)
###############################################

resource "authentik_provider_proxy" "prowlarr" {
  name                  = "prowlarr"
  external_host         = "https://prowlarr.k.oneill.net"
  internal_host         = "http://prowlarr.default.svc.cluster.local:9696"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://prowlarr.k.oneill.net/\d+/api.*
^https://prowlarr.k.oneill.net/api.*
^https://prowlarr.k.oneill.net/\d+/download.*
  EOT
}

resource "authentik_application" "prowlarr" {
  name              = "prowlarr"
  slug              = "prowlarr"
  protocol_provider = authentik_provider_proxy.prowlarr.id
}
