###############################################
# Auto-generated by ak-tool for ara (proxy)
###############################################

resource "authentik_provider_proxy" "ara" {
  name                  = "ara"
  external_host         = "https://ara.k.oneill.net"
  internal_host         = "http://ara-ara-service.ara.svc.cluster.local:8000"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "ara" {
  name              = "ara"
  slug              = "ara"
  protocol_provider = authentik_provider_proxy.ara.id
}
