###############################################
# Auto-generated by ak-tool for komga OIDC 1Password item
###############################################

resource "random_password" "komga_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  komga_oidc_client_id = "komga"
  komga_oidc_secret    = random_password.komga_oidc.result
}

resource "onepassword_item" "komga_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "komga-oidc"
  category = "login"

  note_value = "OIDC client for komga. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.komga_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.komga_oidc_secret
    }
  }
}
