###############################################
# Auto-generated by ak-tool for frank-www (proxy)
###############################################

resource "authentik_provider_proxy" "frank-www" {
  name                  = "frank-www"
  external_host         = "https://frank.k.oneill.net"
  internal_host         = "http://frank-www.frank.svc.cluster.local:8080"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "frank-www" {
  name              = "frank-www"
  slug              = "frank-www"
  protocol_provider = authentik_provider_proxy.frank-www.id
}
