###############################################
# Auto-generated by ak-tool for qui OIDC 1Password item
###############################################

resource "random_password" "qui_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  qui_oidc_client_id = "qui"
  qui_oidc_secret    = random_password.qui_oidc.result
}

resource "onepassword_item" "qui_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "qui-oidc"
  category = "login"

  note_value = "OIDC client for qui. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.qui_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.qui_oidc_secret
    }
  }
}
