###############################################
# Auto-generated by ak-tool for frank (proxy)
###############################################

resource "authentik_provider_proxy" "frank" {
  name                  = "frank"
  external_host         = "https://frank.k.oneill.net"
  internal_host         = "http://frank.frank.svc.cluster.local:18789"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "frank" {
  name              = "frank"
  slug              = "frank"
  protocol_provider = authentik_provider_proxy.frank.id
}
