###############################################
# Auto-generated by ak-tool for ephemera (proxy)
###############################################

resource "authentik_provider_proxy" "ephemera" {
  name                  = "ephemera"
  external_host         = "https://ephemera.k.oneill.net"
  internal_host         = "http://ephemera.default.svc.cluster.local:8286"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "ephemera" {
  name              = "ephemera"
  slug              = "ephemera"
  protocol_provider = authentik_provider_proxy.ephemera.id
}
