###############################################
# Auto-generated by ak-tool for minuspod (proxy)
###############################################

resource "authentik_provider_proxy" "minuspod" {
  name                  = "minuspod"
  external_host         = "https://minuspod.k.oneill.net"
  internal_host         = "http://minuspod.minuspod.svc.cluster.local:8000"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "minuspod" {
  name              = "minuspod"
  slug              = "minuspod"
  protocol_provider = authentik_provider_proxy.minuspod.id
}
