###############################################
# Auto-generated by ak-tool for paperless-ngx OIDC 1Password item
###############################################

resource "random_password" "paperless_ngx_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  paperless_ngx_oidc_client_id = "paperless-ngx"
  paperless_ngx_oidc_secret    = random_password.paperless_ngx_oidc.result
}

resource "onepassword_item" "paperless_ngx_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "paperless-ngx-oidc"
  category = "login"

  note_value = "OIDC client for paperless-ngx. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.paperless_ngx_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.paperless_ngx_oidc_secret
    }
  }
}
