###############################################
# Auto-generated by ak-tool for pinepods OIDC 1Password item
###############################################

resource "random_password" "pinepods_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  pinepods_oidc_client_id = "pinepods"
  pinepods_oidc_secret    = random_password.pinepods_oidc.result
}

resource "onepassword_item" "pinepods_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "pinepods-oidc"
  category = "login"

  note_value = "OIDC client for pinepods. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.pinepods_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.pinepods_oidc_secret
    }
  }
}
