###############################################
# Auto-generated by ak-tool for tautulli (proxy)
###############################################

resource "authentik_provider_proxy" "tautulli" {
  name                  = "tautulli"
  external_host         = "https://tautulli.k.oneill.net"
  internal_host         = "http://tautulli.default.svc.cluster.local:8181"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://tautulli.k.oneill.net/api(/|$)
  EOT
}

resource "authentik_application" "tautulli" {
  name              = "tautulli"
  slug              = "tautulli"
  protocol_provider = authentik_provider_proxy.tautulli.id
}
