###############################################
# Auto-generated by ak-tool for felix-www (proxy)
###############################################

resource "authentik_provider_proxy" "felix-www" {
  name                  = "felix-www"
  external_host         = "https://felix.k.oneill.net"
  internal_host         = "http://felix-www.felix.svc.cluster.local:8080"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "felix-www" {
  name              = "felix-www"
  slug              = "felix-www"
  protocol_provider = authentik_provider_proxy.felix-www.id
}
