###############################################
# Auto-generated by ak-tool for argocd (OIDC)
###############################################

resource "authentik_provider_oauth2" "argocd" {
  name               = "argocd"
  client_id          = local.argocd_oidc_client_id
  client_secret      = local.argocd_oidc_secret
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [{ url = "https://argocd.k.oneill.net/api/dex/callback", matching_mode = "strict" }]
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "argocd" {
  name              = "argocd"
  slug              = "argocd"
  protocol_provider = authentik_provider_oauth2.argocd.id
}
