###############################################
# Auto-generated by ak-tool for shelfmark (OIDC)
###############################################

resource "authentik_provider_oauth2" "shelfmark" {
  name               = "shelfmark"
  client_id          = local.shelfmark_oidc_client_id
  client_secret      = local.shelfmark_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://shelfmark.k.oneill.net/api/auth/oidc/callback", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "shelfmark" {
  name              = "shelfmark"
  slug              = "shelfmark"
  protocol_provider = authentik_provider_oauth2.shelfmark.id
}
