###############################################
# Auto-generated by ak-tool for homepage (proxy)
###############################################

resource "authentik_provider_proxy" "homepage" {
  name                  = "homepage"
  external_host         = "https://homepage.k.oneill.net"
  internal_host         = "http://homepage.default.svc.cluster.local:3000"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "homepage" {
  name              = "homepage"
  slug              = "homepage"
  protocol_provider = authentik_provider_proxy.homepage.id
}
