###############################################
# Auto-generated by ak-tool for cwa-downloader (proxy)
###############################################

resource "authentik_provider_proxy" "cwa-downloader" {
  name                  = "cwa-downloader"
  external_host         = "https://cwa-downloader.k.oneill.net"
  internal_host         = "http://cwa-downloader.default.svc.cluster.local:8084"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "cwa-downloader" {
  name              = "cwa-downloader"
  slug              = "cwa-downloader"
  protocol_provider = authentik_provider_proxy.cwa-downloader.id
}
