###############################################
# Auto-generated by ak-tool for karakeep (OIDC)
###############################################

resource "authentik_provider_oauth2" "karakeep" {
  name               = "karakeep"
  client_id          = local.karakeep_oidc_client_id
  client_secret      = local.karakeep_oidc_secret
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [{ url = "https://karakeep.k.oneill.net/api/auth/callback/custom", matching_mode = "strict" }]
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "karakeep" {
  name              = "karakeep"
  slug              = "karakeep"
  protocol_provider = authentik_provider_oauth2.karakeep.id
}
