###############################################
# Auto-generated by ak-tool for frank-syncthing (proxy)
###############################################

resource "authentik_provider_proxy" "frank-syncthing" {
  name                  = "frank-syncthing"
  external_host         = "https://frank-syncthing.k.oneill.net"
  internal_host         = "http://frank-syncthing-gui.frank.svc.cluster.local:8384"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "frank-syncthing" {
  name              = "frank-syncthing"
  slug              = "frank-syncthing"
  protocol_provider = authentik_provider_proxy.frank-syncthing.id
}
