###############################################
# Auto-generated by ak-tool for paperless-ngx (OIDC)
###############################################

resource "authentik_provider_oauth2" "paperless-ngx" {
  name               = "paperless-ngx"
  client_id          = local.paperless_ngx_oidc_client_id
  client_secret      = local.paperless_ngx_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://paperless.k.oneill.net/accounts/oidc/authentik/login/callback/", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "paperless-ngx" {
  name              = "paperless-ngx"
  slug              = "paperless-ngx"
  protocol_provider = authentik_provider_oauth2.paperless-ngx.id
}
