###############################################
# Auto-generated by ak-tool for shelfmark-comics OIDC 1Password item
###############################################

resource "random_password" "shelfmark_comics_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  shelfmark_comics_oidc_client_id = "shelfmark-comics"
  shelfmark_comics_oidc_secret    = random_password.shelfmark_comics_oidc.result
}

resource "onepassword_item" "shelfmark_comics_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "shelfmark-comics-oidc"
  category = "login"

  note_value = "OIDC client for shelfmark-comics. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.shelfmark_comics_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.shelfmark_comics_oidc_secret
    }
  }
}
