###############################################
# Auto-generated by ak-tool for dawarich OIDC 1Password item
###############################################

resource "random_password" "dawarich_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  dawarich_oidc_client_id = "dawarich"
  dawarich_oidc_secret    = random_password.dawarich_oidc.result
}

resource "onepassword_item" "dawarich_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "dawarich-oidc"
  category = "login"

  note_value = "OIDC client for dawarich. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.dawarich_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.dawarich_oidc_secret
    }
  }
}
