###############################################
# Auto-generated by ak-tool for grafana (OIDC)
###############################################

resource "authentik_provider_oauth2" "grafana" {
  name               = "grafana"
  client_id          = local.grafana_oidc_client_id
  client_secret      = local.grafana_oidc_secret
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [{ url = "https://grafana.k.oneill.net/login/generic_oauth", matching_mode = "strict" }]
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "grafana" {
  name              = "grafana"
  slug              = "grafana"
  protocol_provider = authentik_provider_oauth2.grafana.id
}
