###############################################
# Auto-generated by ak-tool for speakr OIDC 1Password item
###############################################

resource "random_password" "speakr_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  speakr_oidc_client_id = "speakr"
  speakr_oidc_secret    = random_password.speakr_oidc.result
}

resource "onepassword_item" "speakr_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "speakr-oidc"
  category = "login"

  note_value = "OIDC client for speakr. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.speakr_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.speakr_oidc_secret
    }
  }
}
