###############################################
# Auto-generated by ak-tool for sabnzbd (proxy)
###############################################

resource "authentik_provider_proxy" "sabnzbd" {
  name                  = "sabnzbd"
  external_host         = "https://sabnzbd.k.oneill.net"
  internal_host         = "http://sabnzbd.default.svc.cluster.local:8080"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://sabnzbd.k.oneill.net/api(/|$)
  EOT
}

resource "authentik_application" "sabnzbd" {
  name              = "sabnzbd"
  slug              = "sabnzbd"
  protocol_provider = authentik_provider_proxy.sabnzbd.id
}
