###############################################
# Auto-generated by ak-tool for goldilocks (proxy)
###############################################

resource "authentik_provider_proxy" "goldilocks" {
  name                  = "goldilocks"
  external_host         = "https://goldilocks.k.oneill.net"
  internal_host         = "http://goldilocks-dashboard.default.svc.cluster.local:80"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "goldilocks" {
  name              = "goldilocks"
  slug              = "goldilocks"
  protocol_provider = authentik_provider_proxy.goldilocks.id
}
