###############################################
# Auto-generated by ak-tool for netdata (proxy)
###############################################

resource "authentik_provider_proxy" "netdata" {
  name                  = "netdata"
  external_host         = "https://netdata.k.oneill.net"
  internal_host         = "http://netdata.netdata.svc.cluster.local:80"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "netdata" {
  name              = "netdata"
  slug              = "netdata"
  protocol_provider = authentik_provider_proxy.netdata.id
}
