###############################################
# Auto-generated by ak-tool for felix-dashboard OIDC 1Password item
###############################################

resource "random_password" "felix_dashboard_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  felix_dashboard_oidc_client_id = "felix-dashboard"
  felix_dashboard_oidc_secret    = random_password.felix_dashboard_oidc.result
}

resource "onepassword_item" "felix_dashboard_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "felix-dashboard-oidc"
  category = "login"

  note_value = "OIDC client for felix-dashboard. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.felix_dashboard_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.felix_dashboard_oidc_secret
    }
  }
}
