###############################################
# Auto-generated by ak-tool for frigate (proxy)
###############################################

resource "authentik_provider_proxy" "frigate" {
  name                  = "frigate"
  external_host         = "https://frigate.k.oneill.net"
  internal_host         = "http://frigate.frigate.svc.cluster.local:5000"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "frigate" {
  name              = "frigate"
  slug              = "frigate"
  protocol_provider = authentik_provider_proxy.frigate.id
}
