###############################################
# Auto-generated by ak-tool for bambuddy (OIDC)
###############################################

resource "authentik_provider_oauth2" "bambuddy" {
  name          = "bambuddy"
  client_id     = local.bambuddy_oidc_client_id
  client_secret = local.bambuddy_oidc_secret
  client_type   = "confidential"
  grant_types = [
    "authorization_code",
    "hybrid",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code",
    "refresh_token",
  ]
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://bambuddy.k.oneill.net/api/v1/auth/oidc/callback", matching_mode = "strict", redirect_uri_type = "authorization" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "bambuddy" {
  name              = "bambuddy"
  slug              = "bambuddy"
  protocol_provider = authentik_provider_oauth2.bambuddy.id
}
