###############################################
# Auto-generated by ak-tool for autobrr OIDC 1Password item
###############################################

resource "random_password" "autobrr_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  autobrr_oidc_client_id = "autobrr"
  autobrr_oidc_secret    = random_password.autobrr_oidc.result
}

resource "onepassword_item" "autobrr_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "autobrr-oidc"
  category = "login"

  note_value = "OIDC client for autobrr. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.autobrr_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.autobrr_oidc_secret
    }
  }
}
