###############################################
# Auto-generated by ak-tool for bookshelf (proxy)
###############################################

resource "authentik_provider_proxy" "bookshelf" {
  name                  = "bookshelf"
  external_host         = "https://bookshelf.k.oneill.net"
  internal_host         = "http://bookshelf.default.svc.cluster.local:8787"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://bookshelf.k.oneill.net/api(/|$)
  EOT
}

resource "authentik_application" "bookshelf" {
  name              = "bookshelf"
  slug              = "bookshelf"
  protocol_provider = authentik_provider_proxy.bookshelf.id
}
