###############################################
# Auto-generated by ak-tool for booklore OIDC 1Password item
###############################################

resource "random_password" "booklore_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  booklore_oidc_client_id = "booklore"
  booklore_oidc_secret    = random_password.booklore_oidc.result
}

resource "onepassword_item" "booklore_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "booklore-oidc"
  category = "login"

  note_value = "OIDC client for booklore. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.booklore_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.booklore_oidc_secret
    }
  }
}
