###############################################
# Auto-generated by ak-tool for openclaw (proxy)
###############################################

resource "authentik_provider_proxy" "openclaw" {
  name                  = "openclaw"
  external_host         = "https://openclaw.k.oneill.net"
  internal_host         = "http://frank.openclaw.svc.cluster.local:18789"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "openclaw" {
  name              = "openclaw"
  slug              = "openclaw"
  protocol_provider = authentik_provider_proxy.openclaw.id
}
