###############################################
# Auto-generated by ak-tool for smokeping (proxy)
###############################################

resource "authentik_provider_proxy" "smokeping" {
  name                  = "smokeping"
  external_host         = "https://smokeping.k.oneill.net"
  internal_host         = "http://smokeping.default.svc.cluster.local:80"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "smokeping" {
  name              = "smokeping"
  slug              = "smokeping"
  protocol_provider = authentik_provider_proxy.smokeping.id
}
