###############################################
# Auto-generated by ak-tool for speakr (OIDC)
###############################################

resource "authentik_provider_oauth2" "speakr" {
  name               = "speakr"
  client_id          = local.speakr_oidc_client_id
  client_secret      = local.speakr_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://speakr.k.oneill.net/auth/sso/callback", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "speakr" {
  name              = "speakr"
  slug              = "speakr"
  protocol_provider = authentik_provider_oauth2.speakr.id
}
