###############################################
# Auto-generated by ak-tool for grafana (proxy)
###############################################

resource "authentik_provider_proxy" "grafana" {
  name                  = "grafana"
  external_host         = "https://grafana.k.oneill.net"
  internal_host         = "http://grafana.default.svc.cluster.local:80"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "grafana" {
  name              = "grafana"
  slug              = "grafana"
  protocol_provider = authentik_provider_proxy.grafana.id
}
