###############################################
# Auto-generated by ak-tool for bambuddy OIDC 1Password item
###############################################

resource "random_password" "bambuddy_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  bambuddy_oidc_client_id = "bambuddy"
  bambuddy_oidc_secret    = random_password.bambuddy_oidc.result
}

resource "onepassword_item" "bambuddy_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "bambuddy-oidc"
  category = "login"

  note_value = "OIDC client for bambuddy. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.bambuddy_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.bambuddy_oidc_secret
    }
  }
}
