###############################################
# Auto-generated by ak-tool for changedetection (proxy)
###############################################

resource "authentik_provider_proxy" "changedetection" {
  name                  = "changedetection"
  external_host         = "https://changedetection.k.oneill.net"
  internal_host         = "http://changedetection.default.svc.cluster.local:5000"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "changedetection" {
  name              = "changedetection"
  slug              = "changedetection"
  protocol_provider = authentik_provider_proxy.changedetection.id
}
