###############################################
# Auto-generated by ak-tool for semaphore OIDC 1Password item
###############################################

resource "random_password" "semaphore_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  semaphore_oidc_client_id = "semaphore"
  semaphore_oidc_secret    = random_password.semaphore_oidc.result
}

resource "onepassword_item" "semaphore_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "semaphore-oidc"
  category = "login"

  note_value = "OIDC client for semaphore. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.semaphore_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.semaphore_oidc_secret
    }
  }
}
