###############################################
# Auto-generated by ak-tool for huntarr (proxy)
###############################################

resource "authentik_provider_proxy" "huntarr" {
  name                  = "huntarr"
  external_host         = "https://huntarr.k.oneill.net"
  internal_host         = "http://huntarr.default.svc.cluster.local:9705"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "huntarr" {
  name              = "huntarr"
  slug              = "huntarr"
  protocol_provider = authentik_provider_proxy.huntarr.id
}
