###############################################
# Auto-generated by ak-tool for felix-dashboard (OIDC)
###############################################

resource "authentik_provider_oauth2" "felix-dashboard" {
  name          = "felix-dashboard"
  client_id     = local.felix_dashboard_oidc_client_id
  client_secret = local.felix_dashboard_oidc_secret
  client_type   = "public"
  grant_types = [
    "authorization_code",
    "hybrid",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code",
    "refresh_token",
  ]
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://felix-dashboard.k.oneill.net/auth/callback", matching_mode = "strict", redirect_uri_type = "authorization" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "felix-dashboard" {
  name              = "felix-dashboard"
  slug              = "felix-dashboard"
  protocol_provider = authentik_provider_oauth2.felix-dashboard.id
}
