###############################################
# Auto-generated by ak-tool for shelfmark OIDC 1Password item
###############################################

resource "random_password" "shelfmark_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  shelfmark_oidc_client_id = "shelfmark"
  shelfmark_oidc_secret    = random_password.shelfmark_oidc.result
}

resource "onepassword_item" "shelfmark_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "shelfmark-oidc"
  category = "login"

  note_value = "OIDC client for shelfmark. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.shelfmark_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.shelfmark_oidc_secret
    }
  }
}
