###############################################
# Auto-generated by ak-tool for readest-hardcover-sync (proxy)
###############################################

resource "authentik_provider_proxy" "readest-hardcover-sync" {
  name                  = "readest-hardcover-sync"
  external_host         = "https://readest-hardcover-sync.k.oneill.net"
  internal_host         = "http://readest-hardcover-sync.readest-hardcover-sync.svc.cluster.local:8080"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "readest-hardcover-sync" {
  name              = "readest-hardcover-sync"
  slug              = "readest-hardcover-sync"
  protocol_provider = authentik_provider_proxy.readest-hardcover-sync.id
}
