###############################################
# Auto-generated by ak-tool for argocd OIDC 1Password item
###############################################

resource "random_password" "argocd_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  argocd_oidc_client_id = "argocd"
  argocd_oidc_secret    = random_password.argocd_oidc.result
}

resource "onepassword_item" "argocd_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "argocd-oidc"
  category = "login"

  note_value = "OIDC client for argocd. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.argocd_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.argocd_oidc_secret
    }
  }
}
