###############################################
# Auto-generated by ak-tool for immich OIDC 1Password item
###############################################

resource "random_password" "immich_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  immich_oidc_client_id = "immich"
  immich_oidc_secret    = random_password.immich_oidc.result
}

resource "onepassword_item" "immich_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "immich-oidc"
  category = "login"

  note_value = "OIDC client for immich. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.immich_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.immich_oidc_secret
    }
  }
}
