###############################################
# Auto-generated by ak-tool for audiobookshelf OIDC 1Password item
###############################################

resource "random_password" "audiobookshelf_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  audiobookshelf_oidc_client_id = "audiobookshelf"
  audiobookshelf_oidc_secret    = random_password.audiobookshelf_oidc.result
}

resource "onepassword_item" "audiobookshelf_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "audiobookshelf-oidc"
  category = "login"

  note_value = "OIDC client for audiobookshelf. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.audiobookshelf_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.audiobookshelf_oidc_secret
    }
  }
}
