###############################################
# Auto-generated by ak-tool for alertmanager (proxy)
###############################################

resource "authentik_provider_proxy" "alertmanager" {
  name                  = "alertmanager"
  external_host         = "https://alertmanager.k.oneill.net"
  internal_host         = "http://alertmanager.default.svc.cluster.local:9093"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "alertmanager" {
  name              = "alertmanager"
  slug              = "alertmanager"
  protocol_provider = authentik_provider_proxy.alertmanager.id
}
