###############################################
# Auto-generated by ak-tool for homepage OIDC 1Password item
###############################################

resource "random_password" "homepage_oidc" {
  length  = 32
  special = false
}

locals {
  # OpenTofu is the source of truth for OIDC client credentials
  homepage_oidc_client_id = "homepage"
  homepage_oidc_secret    = random_password.homepage_oidc.result
}

resource "onepassword_item" "homepage_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "homepage-oidc"
  category = "login"

  note_value = "OIDC client for homepage. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.homepage_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.homepage_oidc_secret
    }
  }
}
