###############################################
# Auto-generated by ak-tool Outpost
###############################################

resource "authentik_outpost" "embedded" {
  name               = "authentik Embedded Outpost"
  type               = "proxy"
  service_connection = data.authentik_service_connection_kubernetes.local.id
  protocol_providers = [
    authentik_provider_proxy.alertmanager.id,
    authentik_provider_proxy.ara.id,
    authentik_provider_proxy.bazarr.id,
    authentik_provider_proxy.bookshelf.id,
    authentik_provider_proxy.changedetection.id,
    authentik_provider_proxy.frank.id,
    authentik_provider_proxy.goldilocks.id,
    authentik_provider_proxy.healthchecks.id,
    authentik_provider_proxy.homepage.id,
    authentik_provider_proxy.huntarr.id,
    authentik_provider_proxy.prometheus.id,
    authentik_provider_proxy.prowlarr.id,
    authentik_provider_proxy.qbit-manage.id,
    authentik_provider_proxy.radarr.id,
    authentik_provider_proxy.smokeping.id,
    authentik_provider_proxy.sonarr.id,
    authentik_provider_proxy.tautulli.id,
  ]
}
