###############################################
# Auto-generated by ak-tool for qbit-manage (proxy)
###############################################

resource "authentik_provider_proxy" "qbit-manage" {
  name                  = "qbit-manage"
  external_host         = "https://qbit-manage.k.oneill.net"
  internal_host         = "http://qbit-manage.default.svc.cluster.local:8080"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "qbit-manage" {
  name              = "qbit-manage"
  slug              = "qbit-manage"
  protocol_provider = authentik_provider_proxy.qbit-manage.id
}
