###############################################
# Auto-generated by ak-tool for prometheus (proxy)
###############################################

resource "authentik_provider_proxy" "prometheus" {
  name                  = "prometheus"
  external_host         = "https://prometheus.k.oneill.net"
  internal_host         = "http://prometheus.default.svc.cluster.local:9090"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


  skip_path_regex = <<-EOT
^https://prometheus.k.oneill.net/api/.*
  EOT
}

resource "authentik_application" "prometheus" {
  name              = "prometheus"
  slug              = "prometheus"
  protocol_provider = authentik_provider_proxy.prometheus.id
}
