###############################################
# Auto-generated by ak-tool for immich (OIDC)
###############################################

resource "authentik_provider_oauth2" "immich" {
  name               = "immich"
  client_id          = local.immich_oidc_client_id
  client_secret      = local.immich_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://immich.k.oneill.net/auth/login", matching_mode = "strict" },
    { url = "https://immich.k.oneill.net/user-settings", matching_mode = "strict" },
    { url = "app.immich:///oauth-callback", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "immich" {
  name              = "immich"
  slug              = "immich"
  protocol_provider = authentik_provider_oauth2.immich.id
}
