###############################################
# Auto-generated by ak-tool for audiobookshelf (OIDC)
###############################################

resource "authentik_provider_oauth2" "audiobookshelf" {
  name               = "audiobookshelf"
  client_id          = local.audiobookshelf_oidc_client_id
  client_secret      = local.audiobookshelf_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://audiobookshelf.k.oneill.net/auth/openid/callback", matching_mode = "strict" },
    { url = "shelfplayer://callback", matching_mode = "strict" },
    { url = "https://audiobookshelf.k.oneill.net/auth/openid/mobile-redirect", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "audiobookshelf" {
  name              = "audiobookshelf"
  slug              = "audiobookshelf"
  protocol_provider = authentik_provider_oauth2.audiobookshelf.id
}
