###############################################
# Auto-generated by ak-tool for grafana OIDC 1Password item
###############################################

resource "random_password" "grafana_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  grafana_oidc_client_id = "grafana"
  grafana_oidc_secret    = random_password.grafana_oidc.result
}

resource "onepassword_item" "grafana_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "grafana-oidc"
  category = "login"

  note_value = "OIDC client for grafana. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.grafana_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.grafana_oidc_secret
    }
  }
}
