###############################################
# Auto-generated by ak-tool for booklore (OIDC)
###############################################

resource "authentik_provider_oauth2" "booklore" {
  name               = "booklore"
  client_id          = local.booklore_oidc_client_id
  client_secret      = local.booklore_oidc_secret
  client_type        = "public"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [
    { url = "https://booklore.k.oneill.net/oauth2-callback", matching_mode = "strict" },
  ]
  signing_key = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "booklore" {
  name              = "booklore"
  slug              = "booklore"
  protocol_provider = authentik_provider_oauth2.booklore.id
}
