###############################################
# Auto-generated by ak-tool for bazarr (proxy)
###############################################

resource "authentik_provider_proxy" "bazarr" {
  name                  = "bazarr"
  external_host         = "https://bazarr.k.oneill.net"
  internal_host         = "http://bazarr.default.svc.cluster.local:6767"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://bazarr.k.oneill.net/api(/|$)
  EOT
}

resource "authentik_application" "bazarr" {
  name              = "bazarr"
  slug              = "bazarr"
  protocol_provider = authentik_provider_proxy.bazarr.id
}
