###############################################
# Auto-generated by ak-tool for sonarr (proxy)
###############################################

resource "authentik_provider_proxy" "sonarr" {
  name                  = "sonarr"
  external_host         = "https://sonarr.k.oneill.net"
  internal_host         = "http://sonarr.default.svc.cluster.local:8989"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"

  basic_auth_enabled            = true
  basic_auth_username_attribute = "username"
  basic_auth_password_attribute = "password"

  skip_path_regex = <<-EOT
^https://sonarr.k.oneill.net/api/v\d+.*
  EOT
}

resource "authentik_application" "sonarr" {
  name              = "sonarr"
  slug              = "sonarr"
  protocol_provider = authentik_provider_proxy.sonarr.id
}
