###############################################
# Auto-generated by ak-tool for autobrr (OIDC)
###############################################

resource "authentik_provider_oauth2" "autobrr" {
  name               = "autobrr"
  client_id          = local.autobrr_oidc_client_id
  client_secret      = local.autobrr_oidc_secret
  client_type        = "confidential"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id
  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]
  access_token_validity = "hours=1"
  allowed_redirect_uris = [{ url = "https://autobrr.k.oneill.net/api/auth/oidc/callback", matching_mode = "strict" }]
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
}

resource "authentik_application" "autobrr" {
  name              = "autobrr"
  slug              = "autobrr"
  protocol_provider = authentik_provider_oauth2.autobrr.id
}
