###############################################
# Auto-generated by ak-tool for bookbridge (proxy)
###############################################

resource "authentik_provider_proxy" "bookbridge" {
  name                  = "bookbridge"
  external_host         = "https://bookbridge.k.oneill.net"
  internal_host         = "http://bookbridge.bookbridge.svc.cluster.local:5757"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


}

resource "authentik_application" "bookbridge" {
  name              = "bookbridge"
  slug              = "bookbridge"
  protocol_provider = authentik_provider_proxy.bookbridge.id
}
