###############################################
# Auto-generated by ak-tool for karakeep OIDC 1Password item
###############################################

resource "random_password" "karakeep_oidc" {
  length  = 32
  special = false
}

locals {
  # Terraform is the source of truth for OIDC client credentials
  karakeep_oidc_client_id = "karakeep"
  karakeep_oidc_secret    = random_password.karakeep_oidc.result
}

resource "onepassword_item" "karakeep_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "karakeep-oidc"
  category = "login"

  note_value = "OIDC client for karakeep. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.karakeep_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.karakeep_oidc_secret
    }
  }
}
