###############################################
# Auto-generated by ak-tool for storyteller OIDC 1Password item
###############################################

resource "random_password" "storyteller_oidc" {
  length  = 32
  special = false
}

locals {
  # OpenTofu is the source of truth for OIDC client credentials
  storyteller_oidc_client_id = "storyteller"
  storyteller_oidc_secret    = random_password.storyteller_oidc.result
}

resource "onepassword_item" "storyteller_oidc" {
  vault    = var.onepassword_vault_uuid
  title    = "storyteller-oidc"
  category = "login"

  note_value = "OIDC client for storyteller. Managed by OpenTofu — do not edit manually."

  section {
    label = "OIDC"
    field {
      label = "client-id"
      type  = "STRING"
      value = local.storyteller_oidc_client_id
    }
    field {
      label = "client-secret"
      type  = "CONCEALED"
      value = local.storyteller_oidc_secret
    }
  }
}
