###############################################
# Auto-generated by ak-tool for camofox (proxy)
###############################################

resource "authentik_provider_proxy" "camofox" {
  name                  = "camofox"
  external_host         = "https://camofox.k.oneill.net"
  internal_host         = "http://camofox.camofox.svc.cluster.local:6080"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "days=365"


}

resource "authentik_application" "camofox" {
  name              = "camofox"
  slug              = "camofox"
  protocol_provider = authentik_provider_proxy.camofox.id
}
