###############################################
# Auto-generated by ak-tool for hortusfox (proxy)
###############################################

resource "authentik_provider_proxy" "hortusfox" {
  name                  = "hortusfox"
  external_host         = "https://hortusfox.k.oneill.net"
  internal_host         = "http://hortusfox.hortusfox.svc.cluster.local:80"
  mode                  = "forward_domain"
  cookie_domain         = "oneill.net"
  authorization_flow    = data.authentik_flow.default_authorization.id
  invalidation_flow     = data.authentik_flow.default_invalidation.id
  access_token_validity = "hours=1"


  skip_path_regex = <<-EOT
^https://hortusfox.k.oneill.net/(api|cronjob)(/|$)
  EOT
}

resource "authentik_application" "hortusfox" {
  name              = "hortusfox"
  slug              = "hortusfox"
  protocol_provider = authentik_provider_proxy.hortusfox.id
}
