---
# Source: unpoller/templates/unpoller-config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unpoller-config
  labels:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/instance: unpoller
    app.kubernetes.io/version: "v2.21.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  up.conf: |
    [unifi.defaults]
      url = "https://udmp.oneill.net"
      # Non-default: the UDMP hostname presents a valid certificate.
      verify_ssl = true
    [influxdb]
      disable = true
