#!/usr/bin/env bash

set -eu -o pipefail

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASEDIR"

source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir -p tmp helm/paperless-ngx helm/valkey

helm_template paperless-ngx paperless-ngx --namespace paperless-ngx --values values.yaml --output-dir tmp
mv tmp/paperless-ngx/templates/* helm/paperless-ngx/

helm_template paperless-valkey valkey --namespace paperless-ngx --values valkey-values.yaml --output-dir tmp
mv tmp/valkey/templates/* helm/valkey/

rm -rf helm/*/tests
rm -rf tmp
