#!/bin/bash

set -eu -o pipefail

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASEDIR"

# Source the chart-version helper
source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir tmp helm

helm_template traefik traefik \
	--include-crds \
	--namespace traefik \
	--values values.yaml \
	--create-namespace \
	--api-versions policy/v1/PodDisruptionBudget \
	--output-dir tmp

mv tmp/*/* helm
rmdir tmp/*
rmdir tmp
rm -rf helm/tests
