---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: healthchecks

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: healthchecks
      property: secret-key
  - secretKey: EMAIL_HOST_PASSWORD
    remoteRef:
      key: smtp-relay
      property: relay-password
  - secretKey: CANARY_PING_KEY
    remoteRef:
      key: healthchecks
      property: canary-ping-key
  - secretKey: HEALTHCHECK_API_KEY
    remoteRef:
      key: healthchecks
      property: api-key
  - secretKey: HEALTHCHECK_PING_KEY
    remoteRef:
      key: healthchecks
      property: PING_KEY
  target:
    name: healthchecks
