---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthchecks

components:
- ../components/authentik

resources:
- namespace.yaml
- externalsecret.yaml
- postgres-cluster.yaml
- helm/healthchecks/common.yaml
- cronjob-canary-ping.yaml
- cronjob-channel-audit.yaml
- tailscale-ingress.yaml

configMapGenerator:
- name: channel-audit-script
  files:
  - audit-channels

commonAnnotations:
  argoManaged: 'true'
