---
services:
  nut_webgui:
    # renovate: datasource=docker
    image: ghcr.io/superioone/nut_webgui:0.10.0@sha256:99eaacb1603c722db3415fd64911e2f37cad0bc1810508178a8e1fa14d2972d3
    restart: unless-stopped
    env_file:
      - nut_webgui.env
    labels:
      # Enable Traefik for this container (since exposedbydefault=false)
      - "traefik.enable=true"
      # Define the routing rule: route traffic for nut.oneill.net to this service
      - "traefik.http.routers.nut_webgui.rule=Host(`nut.oneill.net`)"
      # Use the "websecure" entrypoint (port 443) for this router
      - "traefik.http.routers.nut_webgui.entrypoints=websecure"
      # Enable TLS and use the "letsencrypt" certificate resolver for auto-HTTPS
      - "traefik.http.routers.nut_webgui.tls.certresolver=letsencrypt"
      # Tell Traefik which port nut_webgui is listening on (9000)
      - "traefik.http.services.nut_webgui.loadbalancer.server.port=9000"
    networks:
      - traefik

networks:
  traefik:
    external: true
