---
# Source: kured/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured
  namespace: kured
  labels:
    app.kubernetes.io/name: kured
    app.kubernetes.io/instance: kured
    app.kubernetes.io/managed-by: Helm
  annotations:
