---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: alertmanager

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    template:
      mergePolicy: Merge
      data:
        HEALTHCHECKS_WATCHDOG_URL: 'https://hc.k.oneill.net/ping/{{ .HEALTHCHECKS_PING_KEY }}/prometheus-watchdog'
  data:
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: smtp-relay
      property: relay-password
  - secretKey: SLACK_WEBHOOK_URL
    remoteRef:
      key: alertmanager
      property: SLACK_WEBHOOK_URL
  - secretKey: HEALTHCHECKS_PING_KEY
    remoteRef:
      key: healthchecks
      property: PING_KEY
