---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: storyteller-oidc

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: storyteller-oidc
    creationPolicy: Owner
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: storyteller-oidc
      property: client-id
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: storyteller-oidc
      property: client-secret
