---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: storyteller-secrets

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: storyteller-secrets
    creationPolicy: Owner
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: STORYTELLER_SECRET_KEY
    sourceRef:
      generatorRef:
        kind: Password
        name: storyteller-secret-key
