---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: acme-sh-credentials

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: acme-sh-credentials
  data:
  - secretKey: syno-username
    remoteRef:
      key: synology-acme
      property: username
  - secretKey: syno-password
    remoteRef:
      key: synology-acme
      property: password
  - secretKey: zerossl-eab-secret
    remoteRef:
      key: cert-manager
      property: zerossl-eab-secret
  - secretKey: udmp-ssh-key
    remoteRef:
      key: udmp-acme
      property: udmp-acme.key
  dataFrom:
  - extract:
      key: cloudflare-dns-write
