---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: openarchiver-meilisearch
  namespace: openarchiver

spec:
  serviceName: openarchiver-meilisearch
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openarchiver-meilisearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openarchiver-meilisearch
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: meilisearch
        image: docker.io/getmeili/meilisearch:v1.49.0@sha256:bdc7d7e7939911c40d88d6bcd01f9c72c81f7293135916d48bce241569f721bd
        imagePullPolicy: IfNotPresent
        env:
        - name: MEILI_ENV
          value: production
        - name: MEILI_NO_ANALYTICS
          value: 'true'
        - name: MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE
          value: 'true'
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: openarchiver-secrets
              key: meilisearch-master-key
        ports:
        - name: http
          containerPort: 7700
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /meili_data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
