---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: openarchiver-postgres
  namespace: openarchiver

spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-standard-trixie@sha256:07d07e04eb3ae038576cb394f36cce88fbfc083eb51261fa945cf1a2f19de4f9
  enablePDB: false

  storage:
    size: 20Gi

  bootstrap:
    initdb:
      database: openarchiver
      owner: openarchiver
