#!/usr/bin/env bash

set -eu -o pipefail

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$BASEDIR"

source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir -p tmp helm/valkey

# Render Valkey chart
helm_template valkey valkey --namespace openarchiver --values valkey-values.yaml --output-dir tmp
mv tmp/valkey/templates/* helm/valkey/

# Clean up
rm -rf tmp
rm -rf helm/*/tests
