#!/bin/bash
BASEDIR=$(dirname "$0")
source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp && mkdir tmp helm

# Render Helm chart
helm_template volume-snapshot-controller snapshot-controller \
  --values values.yaml \
  --namespace volume-snapshot-controller \
  --output-dir tmp

mv tmp/*/* helm && rmdir tmp/*
