---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: restic-rest-server-htpasswd
  labels:
    app.kubernetes.io/instance: restic
    app.kubernetes.io/name: rest-server
    app.kubernetes.io/component: rest-server

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: restic-rest-server
  target:
    name: restic-rest-server-htpasswd
    template:
      data:
        .htpasswd: |-
          {{- range $field, $value := . }}
          {{- if hasSuffix "-htpasswd" $field }}
          {{ trimSuffix "-htpasswd" $field }}:{{ $value }}
          {{- end }}
          {{- end }}
