---
configuration:
  backupStorageLocation:
  - name: default
    provider: aws
    bucket: data
    config:
      region: rclone
      s3Url: https://rclone-s3-velero.k.oneill.net
      s3ForcePathStyle: 'true'
      checksumAlgorithm: ''

  volumeSnapshotLocation:
  - name: default
    provider: aws
    config:
      region: us-west-000

  features: EnableCSI
  defaultVolumesToFsBackup: false
  defaultSnapshotMoveData: true

deployNodeAgent: true

nodeAgent:
  privileged: false

uploaderType: kopia

credentials:
  existingSecret: velero-credentials

metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8085'

initContainers:
- name: velero-plugin-for-aws
  # renovate: datasource=docker depName=velero/velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.14.1@sha256:1493a0039cd5cb31004cfbb52f8a1990bc0ed81497ce72516bc76fa9e21506c1
  volumeMounts:
  - mountPath: /target
    name: plugins
