---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: readest-hardcover-sync

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: READEST_EMAIL
    remoteRef:
      key: readest-hardcover-sync
      property: READEST_EMAIL
  - secretKey: READEST_PASSWORD
    remoteRef:
      key: readest-hardcover-sync
      property: READEST_PASSWORD
  - secretKey: HARDCOVER_TOKEN
    remoteRef:
      key: readest-hardcover-sync
      property: HARDCOVER_TOKEN
