---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: readest-hardcover-sync

resources:
- namespace.yaml
- deploy.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- externalsecret.yaml

commonAnnotations:
  argoManaged: 'true'

labels:

- pairs:
    app.kubernetes.io/name: readest-hardcover-sync
    app.kubernetes.io/instance: readest-hardcover-sync
  includeSelectors: true
