---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudflare-ddns
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-ddns
      app.kubernetes.io/instance: cloudflare-ddns
  template:
    metadata:
      name: cloudflare-ddns
      labels:
        app.kubernetes.io/name: cloudflare-ddns
        app.kubernetes.io/instance: cloudflare-ddns
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cloudflare-ddns
        image: docker.io/favonia/cloudflare-ddns:1.17.0@sha256:61013368c8f95981c0bb8bf56d962078d8b4e95724a554fa2dabb20d6e478097
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns
              key: CLOUDFLARE_API_TOKEN
        - name: DOMAINS
          value: luser.fnord.net,luser.oneill.net
