services:
  rtl_433:
    container_name: rtl_433
    # renovate: datasource=docker
    image: hertzg/rtl_433:25.12@sha256:b5e9748b2e74ba857adbdaffbaaab21e2bdaca8f31e08c9abd5dd5082fe8b57c
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - MQTT_USERNAME=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASS}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - TZ=America/New_York
    command:
      - "-f"
      - "915MHz"
      - "-g"
      - "0"
      - "-C"
      - "si"
      - "-F"
      - "json"
      - "-F"
      - "mqtt://${MQTT_HOST}:${MQTT_PORT}/retain=0,base=rtl_433,events=rtl_433/devices[/model][/id]"
      - "-F"
      - "log"
