---
- name: Restart smartd
  ansible.builtin.service:
    name: smartmontools
    state: restarted
  when:
    - common_smartd_enabled is defined
    - common_smartd_enabled | bool

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true
