---
general:
  log_level: VERBOSE
  timer: 10
  private_tracker_handling: obsolete_tag
  obsolete_tag: obsolete

job_defaults:
  max_concurrent_searches: 5

jobs:
  search_unmet_cutoff:
  search_missing:
  remove_failed_imports:
  remove_failed_downloads:
  remove_stalled:
  remove_slow:

download_clients:
  qbittorrent:
  - base_url: http://qbittorrent.default.svc.cluster.local:8080
    username: admin
    password: !ENV QBITTORRENT_PASSWORD

instances:
  sonarr:
  - base_url: http://sonarr.default.svc.cluster.local:8989
    api_key: !ENV SONARR_API_KEY
