---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: decluttarr-sonarr

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: decluttarr
      app.kubernetes.io/instance: decluttarr-sonarr
  template:
    metadata:
      name: decluttarr-sonarr
      labels:
        app.kubernetes.io/name: decluttarr
        app.kubernetes.io/instance: decluttarr-sonarr
      annotations:
        reloader.stakater.com/auto: 'true'
    spec:
      automountServiceAccountToken: false
      containers:
      - name: decluttarr
        image: ghcr.io/manimatter/decluttarr:v2.2.0@sha256:fd3dc206c17df32190cda1bed2ef3ee1cb9726bd108aa7e97e83e47cb3e72d78
        env:
        - name: TZ
          value: America/New_York
        envFrom:
        - secretRef:
            name: decluttarr
        volumeMounts:
        - name: config
          mountPath: /app/config/config.yaml
          subPath: config-sonarr.yaml
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: decluttarr-config
