---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: decluttarr

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: decluttarr
