---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: autobrr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: autobrr
  template:
    metadata:
      labels:
        app: autobrr
    spec:
      containers:
      - name: autobrr
        image: ghcr.io/autobrr/autobrr:v1.80.0@sha256:944b1c438302ed10bef810a49f2eb7f334b5abf578db473bcb8d997db3978227
        ports:
        - containerPort: 7474
        - name: metrics
          containerPort: 9074
        envFrom:
        - secretRef:
            name: autobrr-oidc
        - configMapRef:
            name: autobrr-config
        volumeMounts:
        - mountPath: /config
          name: config
        env:
        - name: TZ
          value: EST5EDT
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: autobrr-config
