---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: autobrr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: autobrr
  template:
    metadata:
      labels:
        app: autobrr
    spec:
      containers:
      - name: autobrr
        image: ghcr.io/autobrr/autobrr:v1.83.0@sha256:7e8ce4ec9397685762dc7d8426c976cb15bd36522fac91dfd3648a4c57c6d358
        ports:
        - containerPort: 7474
        - name: metrics
          containerPort: 9074
        envFrom:
        - secretRef:
            name: autobrr-oidc
        - configMapRef:
            name: autobrr-config
        volumeMounts:
        - mountPath: /config
          name: config
        env:
        - name: TZ
          value: EST5EDT
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: autobrr-config
