---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: autobrr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: autobrr
  template:
    metadata:
      labels:
        app: autobrr
    spec:
      containers:
      - name: autobrr
        image: ghcr.io/autobrr/autobrr:v1.77.0@sha256:7274b735b23ff4d048e7706145ce5759020e4ee6d85bb1fb8cca523784d35f88
        ports:
        - containerPort: 7474
        envFrom:
        - secretRef:
            name: autobrr-oidc
        - configMapRef:
            name: autobrr-config
        volumeMounts:
        - mountPath: /config
          name: config
        env:
        - name: TZ
          value: EST5EDT
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: autobrr-config
