---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

commonAnnotations:
  argoManaged: 'true'

images:
- name: ghcr.io/immich-app/immich-server
  newTag: v3.2.2@sha256:79cc1623323d5894922686d8743b4780181428f98eecbfb58ce12c41ef02d1ea
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v3.2.2-cuda@sha256:38001e84ce46206e9e019d8ee7f567bf55914f019dff8f6a70d02fd93bb14073

resources:
- namespace.yaml
- immich-postgres-cluster.yaml
- externalsecret.yaml
- pvc-library.yaml
- helm/immich/server.yaml
- helm/immich/machine-learning.yaml
- helm/valkey/scripts.yaml
- helm/valkey/service-internal.yaml
- helm/valkey/services.yaml
- helm/valkey/statefulset.yaml
