---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

commonAnnotations:
  argoManaged: 'true'

images:
- name: ghcr.io/immich-app/immich-server
  newTag: v2.3.1@sha256:f8d06a32b1b2a81053d78e40bf8e35236b9faefb5c3903ce9ca8712c9ed78445
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v2.3.1-cuda@sha256:723c82610d713bc9bc15d90d8426f96915c2cbd634ef5bec1bf45a098d82d81d

resources:
- namespace.yaml
- immich-postgres-cluster.yaml
- externalsecret.yaml
- pvc-library.yaml
- helm/immich/server.yaml
- helm/immich/machine-learning.yaml
- helm/valkey/scripts.yaml
- helm/valkey/service-internal.yaml
- helm/valkey/services.yaml
- helm/valkey/statefulset.yaml
