---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

commonAnnotations:
  argoManaged: 'true'

images:
- name: ghcr.io/immich-app/immich-server
  newTag: v3.2.4@sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v3.2.4-cuda@sha256:b9fdebfe7f07ff71f77e9d67d509d83c5e055da486a07c12080669c82a80c65e

resources:
- namespace.yaml
- immich-postgres-cluster.yaml
- externalsecret.yaml
- pvc-library.yaml
- pvc-valkey.yaml
- helm/immich/server.yaml
- helm/immich/machine-learning.yaml
- helm/valkey/scripts.yaml
- helm/valkey/service-internal.yaml
- helm/valkey/services.yaml
- helm/valkey/statefulset.yaml
