#!/usr/bin/env bash

set -eu -o pipefail

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASEDIR"

source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir -p tmp helm/immich helm/valkey

helm_template immich immich --namespace immich --values values.yaml --output-dir tmp
mv tmp/immich/templates/* helm/immich/

helm_template immich-valkey valkey --namespace immich --values valkey-values.yaml --output-dir tmp
mv tmp/valkey/templates/* helm/valkey/

rm -rf helm/*/tests
rm -rf tmp
