---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: prowlarr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:2.3.0@sha256:9ef5d8bf832edcacb6082f9262cb36087854e78eb7b1c3e1d4375056055b2d82
        ports:
        - containerPort: 9696
        volumeMounts:
        - mountPath: /config
          name: config
        env:
        - name: PUID
          value: '10001'
        - name: PGID
          value: '10001'
        - name: TZ
          value: EST5EDT
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-config
