---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: prowlarr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:2.4.0@sha256:4fd7a166c8f46dd3370a871c250ee577d6c2ae97a0dbe0e3614b5ef736205620
        ports:
        - containerPort: 9696
        volumeMounts:
        - mountPath: /config
          name: config
        env:
        - name: PUID
          value: '10001'
        - name: PGID
          value: '10001'
        - name: TZ
          value: EST5EDT
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-config
