---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: exporter-web-config

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: password
    remoteRef:
      key: blackbox-exporter-password
      property: password
  target:
    template:
      engineVersion: v2
      data:
        web-config.yaml: |-
          basic_auth_users:
            prometheus: {{ htpasswd "prometheus" .password "bcrypt" | replace "prometheus:" "" | quote }}
