---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karakeep

resources:
- namespace.yaml
- externalsecret.yaml
- externalsecret-oidc.yaml
- postgres-cluster.yaml
- helm/karakeep/common.yaml
- helm/meilisearch/serviceaccount.yaml
- helm/meilisearch/configmap.yaml
- helm/meilisearch/pvc.yaml
- helm/meilisearch/service.yaml
- helm/meilisearch/statefulset.yaml

commonAnnotations:
  argoManaged: 'true'

images:
- name: ghcr.io/karakeep-app/karakeep
  newTag: 0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c
- name: getmeili/meilisearch
  newTag: v1.49.0@sha256:bdc7d7e7939911c40d88d6bcd01f9c72c81f7293135916d48bce241569f721bd
