---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: felix-secrets

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: felix-secrets
    creationPolicy: Owner
  data:
  - secretKey: API_SERVER_KEY
    remoteRef:
      key: felix
      property: api-server-key
  - secretKey: SLACK_BOT_TOKEN
    remoteRef:
      key: felix
      property: bot-user-oauth-token
  - secretKey: SLACK_APP_TOKEN
    remoteRef:
      key: felix
      property: socket-mode-token
  - secretKey: SLACK_ALLOWED_USERS
    remoteRef:
      key: felix
      property: slack-allowed-users
