---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: felix

components:
- ../components/authentik

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- service-dashboard.yaml
- service-www.yaml
- ingress.yaml
- ingress-dashboard.yaml
- ingress-www.yaml
- externalsecret.yaml
- pvc.yaml
- postgres.yaml
- rbac.yaml

configMapGenerator:
- name: felix-nginx-config
  files:
  - nginx.conf
- name: felix-api-entrypoint
  files:
  - api-entrypoint.sh

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  argoManaged: 'true'

labels:

- pairs:
    app.kubernetes.io/name: felix
    app.kubernetes.io/instance: felix
  includeSelectors: true
