---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: felix-db
  namespace: felix

spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:ebf3919504d7523a63e8e2fee9b051211de714644b36469275558c624afd50ec
  enablePDB: false
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: gametrack
      owner: gametrack
