---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: cert-manager

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: cert-manager
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: cloudflare-dns-write
      property: CF_Token
