---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: homepage-oidc

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: HOMEPAGE_OIDC_CLIENT_ID
    remoteRef:
      key: homepage-oidc
      property: client-id
  - secretKey: HOMEPAGE_OIDC_CLIENT_SECRET
    remoteRef:
      key: homepage-oidc
      property: client-secret
  target:
    name: homepage-oidc
