---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: homepage-auth

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: homepage-auth
    creationPolicy: Owner
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: HOMEPAGE_AUTH_SECRET
    sourceRef:
      generatorRef:
        kind: Password
        name: homepage-auth
