---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonAnnotations:
  argoManaged: 'true'

resources:
- helm/templates/common.yaml
- externalsecret-auth.yaml
- externalsecret-oidc.yaml
- password-generator.yaml

labels:

- pairs:
    app: homepage

configMapGenerator:
- name: homepage
  options:
    disableNameSuffixHash: true
  literals:
  - docker.yaml=""
  - bookmarks.yaml=""
  files:
  - custom.js
  - kubernetes.yaml
  - settings.yaml
  - widgets.yaml
  - services.yaml

patches:

- target:
    kind: Deployment
    name: homepage
  patch: |-
    - op: add
      path: /metadata/annotations/reloader.stakater.com~1auto
      value: "true"
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: homepage-config
        subPath: custom.js
        mountPath: /app/config/custom.js
