---
- Smart Home:
  - NUT WebGUI:
      href: https://nut.oneill.net
      description: UPS Monitoring
      icon: nut-webgui.png
  - Z-Wave JS:
      href: https://zwavejs.oneill.net/
      icon: z-wave-js-ui.png
  - Zigbee2MQTT:
      href: https://zigbee2mqtt.oneill.net/
      icon: zigbee2mqtt.png
  - Matter Server:
      href: https://matter.oneill.net/
      description: Matter/Thread Bridge
      icon: matter.png
  - Thread/OTBR:
      href: https://thread.oneill.net/
      description: OpenThread Border Router
      icon: thread.png

- Server Power:
  - Infra1:
      href: http://infra1-power.oneill.net
      icon: esphome.png
  - P1:
      href: http://p1-power.oneill.net
      icon: esphome.png
  - K5:
      href: http://k5-power.oneill.net
      icon: esphome.png
  - K3:
      href: http://k3-power.oneill.net
      icon: esphome.png
  - K4:
      href: http://k4-power.oneill.net
      icon: esphome.png

- AMT Management:
  - K5:
      href: http://k5-amt.oneill.net:16992
      icon: mdi-chip
  - K3:
      href: http://k3-amt.oneill.net:16992
      icon: mdi-chip
  - K4:
      href: http://k4-amt.oneill.net:16992
      icon: mdi-chip

- Infrastructure:
  - Proxmox:
      href: https://pve.oneill.net
      description: Proxmox Cluster
      icon: proxmox
  - SpiderDuo KVM:
      href: https://spiderduo.oneill.net
      description: SpiderDuo KVM
      icon: mdi-spider-outline
