---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28

# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

# This enables the service account to access the necessary resources
enableRbac: true

# Environment variables
env:
- name: HOMEPAGE_ALLOWED_HOSTS
  value: '*'

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      ak-type: simple
    tls:
    - hosts:
      - homepage.k.oneill.net
      secretName: homepage-tls
    hosts:
    - host: homepage.k.oneill.net
      paths:
      - path: /
        pathType: Prefix
