---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60

# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

# This enables the service account to access the necessary resources
enableRbac: true

# Environment variables
env:
- name: HOMEPAGE_ALLOWED_HOSTS
  value: homepage.k.oneill.net
- name: HOMEPAGE_AUTH_ENABLED
  value: 'true'
- name: HOMEPAGE_AUTH_SECRET
  valueFrom:
    secretKeyRef:
      name: homepage-auth
      key: HOMEPAGE_AUTH_SECRET
- name: HOMEPAGE_EXTERNAL_URL
  value: https://homepage.k.oneill.net
- name: HOMEPAGE_OIDC_ISSUER
  value: https://auth.k.oneill.net/application/o/homepage/
- name: HOMEPAGE_OIDC_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: homepage-oidc
      key: HOMEPAGE_OIDC_CLIENT_ID
- name: HOMEPAGE_OIDC_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: homepage-oidc
      key: HOMEPAGE_OIDC_CLIENT_SECRET
- name: HOMEPAGE_OIDC_NAME
  value: Authentik

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      ak-type: oidc
      ak-oidc-callback: /api/auth/callback/homepage-oidc
    tls:
    - hosts:
      - homepage.k.oneill.net
      secretName: homepage-tls
    hosts:
    - host: homepage.k.oneill.net
      paths:
      - path: /
        pathType: Prefix
