---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1

# The service account is necessary to allow discovery of other services
serviceAccount:
  create: true
  name: homepage

# This enables the service account to access the necessary resources
enableRbac: true

# Environment variables
env:
- name: HOMEPAGE_ALLOWED_HOSTS
  value: '*'

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      ak-type: simple
    tls:
    - hosts:
      - homepage.k.oneill.net
      secretName: homepage-tls
    hosts:
    - host: homepage.k.oneill.net
      paths:
      - path: /
        pathType: Prefix
