---
apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: netdata-child
  namespace: netdata

spec:
  template:
    spec:
      initContainers:
      - name: inject-stream-key
        image: alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
        command:
        - sh
        - -c
        - |
          sed "s/11111111-2222-3333-4444-555555555555/$NETDATA_STREAM_API_KEY/g" \
            /etc/netdata-tmpl/stream > /etc/netdata-out/stream.conf
        envFrom:
        - secretRef:
            name: netdata-streaming
        volumeMounts:
        - name: configmap
          mountPath: /etc/netdata-tmpl
        - name: stream-conf
          mountPath: /etc/netdata-out
