---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: netdata-k8s-state
  namespace: netdata

spec:
  template:
    spec:
      initContainers:
      - name: inject-stream-key
        image: alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
        command:
        - sh
        - -c
        - |
          sed "s/11111111-2222-3333-4444-555555555555/$NETDATA_STREAM_API_KEY/g" \
            /etc/netdata-tmpl/stream > /etc/netdata-out/stream.conf
        envFrom:
        - secretRef:
            name: netdata-streaming
        volumeMounts:
        - name: configmap
          mountPath: /etc/netdata-tmpl
        - name: stream-conf
          mountPath: /etc/netdata-out
