---
apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: netdata-child
  namespace: netdata

spec:
  template:
    spec:
      initContainers:
      - name: inject-stream-key
        image: alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
        command:
        - sh
        - -c
        - |
          sed "s/11111111-2222-3333-4444-555555555555/$NETDATA_STREAM_API_KEY/g" \
            /etc/netdata-tmpl/stream > /etc/netdata-out/stream.conf
        envFrom:
        - secretRef:
            name: netdata-streaming
        volumeMounts:
        - name: configmap
          mountPath: /etc/netdata-tmpl
        - name: stream-conf
          mountPath: /etc/netdata-out
