#!/usr/bin/env bash

set -eu -o pipefail

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$BASEDIR"

source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir -p tmp helm/netdata

# Render the Netdata chart (direct from remote repo via chart-version helper)
helm_template netdata netdata \
  --namespace netdata \
  --values values.yaml \
  --output-dir tmp

mv tmp/netdata/templates/* helm/netdata/

rm -rf tmp
rm -rf helm/*/tests
