---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ara

components:
- ../components/authentik

resources:
- namespace.yaml
- ara-postgres-cluster.yaml
- ara-basic-auth-secret.yaml
- middleware-basic-auth.yaml
- ingress.yaml
- helm/deployment.yaml
- helm/extra-objects.yaml
- helm/pvc.yaml
- helm/service.yaml

patches:
- path: patch-deployment-password.yaml
  target:
    kind: Deployment
    name: ara-ara

images:
- name: docker.io/recordsansible/ara-api
  newTag: latest@sha256:1c52df15a892f691f2e57c541f944ec33ce377f160ed2d01d5aa84d37ccabddc

commonAnnotations:
  argoManaged: 'true'
