---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ollama
  namespace: ollama
  labels:
    app.kubernetes.io/name: ollama
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
    spec:
      runtimeClassName: nvidia
      priorityClassName: gpu-priority
      containers:
      - name: ollama
        image: ollama/ollama:0.21.0@sha256:d3d553bdfbcc7f55dd5ddf42c4cbe3a927aa9bb1802710d35e94656ca5aea02b
        env:
        - name: OLLAMA_CONTEXT_LENGTH
          value: '8192'
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: models
          mountPath: /root/.ollama
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ollama-models
