---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ollama
  namespace: ollama
  labels:
    app.kubernetes.io/name: ollama
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
    spec:
      runtimeClassName: nvidia
      priorityClassName: gpu-priority
      containers:
      - name: ollama
        image: ollama/ollama:0.18.2@sha256:5a5d014aa774f78ebe1340c0d4afc2e35afc12a2c3b34c84e71f78ea20af4ba3
        env:
        - name: OLLAMA_CONTEXT_LENGTH
          value: '8192'
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: models
          mountPath: /root/.ollama
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ollama-models
