---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: kured-notify

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: kured-notify
    template:
      data:
        KURED_NOTIFY_URL: '{{ .webhook | replace "https://hooks.slack.com/services/" "slack://" }}'
  data:
  - secretKey: webhook
    remoteRef:
      key: alertmanager
      property: SLACK_WEBHOOK_URL
