---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kured

resources:
- namespace.yaml
- externalsecret.yaml
- helm/templates/clusterrole.yaml
- helm/templates/clusterrolebinding.yaml
- helm/templates/daemonset.yaml
- helm/templates/role.yaml
- helm/templates/rolebinding.yaml
- helm/templates/serviceaccount.yaml

images:
- name: ghcr.io/kubereboot/kured
  newTag: 1.23.0@sha256:8dfd3c2e889337595731d801afc5c031b545876a29427897b3f711d2983f30c4

commonAnnotations:
  argoManaged: 'true'

labels:

- pairs:
    app: kured
