---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: speakr

resources:
- namespace.yaml
- speakr-postgres-cluster.yaml
- externalsecret.yaml
- externalsecret-oidc.yaml
- pvc-uploads.yaml
- deploy-speakr.yaml
- service-speakr.yaml
- ingress.yaml

commonAnnotations:
  argoManaged: 'true'
