---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: speakr-postgres

spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8
  enablePDB: false

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: speakr
      owner: speakr
