---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: semaphore-postgres

spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-standard-trixie@sha256:1802b367acdc4566fc028e4202d15823f02ba6d10c0cfc5d459bc8b04a77545d
  enablePDB: true

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: semaphore
      owner: semaphore
