---
apiVersion: batch/v1
kind: CronJob

metadata:
  name: cluster-backup
  namespace: kube-system
  annotations:
    goldilocks.fairwinds.com/vpa-update-mode: 'Off'

spec:
  schedule: 0 4 * * *
  timeZone: America/New_York
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          name: cluster-backup
        spec:
          hostNetwork: true
          containers:
          - name: cluster-backup
            image: debian:stable-slim@sha256:04634311a8d5fc442b6eb06d792293c4f3e2268652ca7634e00ce8ef5cc0a28a
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 250m
              limits:
                cpu: 250m
            command:
            - /script/backup
            env:
            - name: HEALTHCHECK_PING_KEY
              valueFrom:
                secretKeyRef:
                  name: healthchecks
                  key: HEALTHCHECK_PING_KEY
            volumeMounts:
            - name: script
              mountPath: /script
            - name: etcd
              mountPath: /var/lib/etcd
              readOnly: true
            - name: k8s
              mountPath: /etc/kubernetes
              readOnly: true
            - name: backups
              mountPath: /backups
          volumes:
          - name: script
            configMap:
              name: cluster-backup
              defaultMode: 0744
          - hostPath:
              path: /var/lib/etcd
            name: etcd
          - hostPath:
              path: /etc/kubernetes
            name: k8s
          - nfs:
              server: fs2.oneill.net
              path: /volume2/backups/cluster-backup
            name: backups
          restartPolicy: OnFailure
          nodeSelector:
            node-role.kubernetes.io/control-plane: ''
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
