---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: sonarr
  annotations:
    reloader.stakater.com/auto: 'true'

spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:4.0.19@sha256:24acea2956a0ccb11f103877d9f4f8576600fb34bff34820ed749c2256dab89f
        ports:
        - containerPort: 8989
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /shared
          name: shared
        env:
        - name: PUID
          value: '10001'
        - name: PGID
          value: '10001'
        - name: TZ
          value: EST5EDT
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - apk add ffmpeg
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - nfs:
          server: fs2.oneill.net
          path: /volume2/shared
        name: shared
