---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: frigate

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: frigate
    creationPolicy: Owner
  data:
  - secretKey: FRIGATE_RTSP_LIVING_ROOM_HIGH
    remoteRef:
      key: frigate
      property: rtsp_living_room_high
  - secretKey: FRIGATE_RTSP_LIVING_ROOM_LOW
    remoteRef:
      key: frigate
      property: rtsp_living_room_low
  - secretKey: FRIGATE_RTSP_G4_INSTANT_HIGH
    remoteRef:
      key: frigate
      property: rtsp_g4_instant_high
  - secretKey: FRIGATE_RTSP_G4_INSTANT_LOW
    remoteRef:
      key: frigate
      property: rtsp_g4_instant_low
  - secretKey: FRIGATE_RTSP_G3_MICRO_HIGH
    remoteRef:
      key: frigate
      property: rtsp_g3_micro_high
  - secretKey: FRIGATE_RTSP_G3_MICRO_LOW
    remoteRef:
      key: frigate
      property: rtsp_g3_micro_low
  - secretKey: FRIGATE_RTSP_GARAGE_HIGH
    remoteRef:
      key: frigate
      property: rtsp_garage_high
  - secretKey: FRIGATE_RTSP_GARAGE_LOW
    remoteRef:
      key: frigate
      property: rtsp_garage_low
  - secretKey: FRIGATE_JWT_SECRET
    remoteRef:
      key: frigate
      property: jwt_secret
  - secretKey: FRIGATE_MQTT_USER
    remoteRef:
      key: frigate
      property: mqtt_user
  - secretKey: FRIGATE_MQTT_PASSWORD
    remoteRef:
      key: frigate
      property: mqtt_password
