---
image:
  tag: 0.17.1-tensorrt@sha256:a8d21fae3d49aea25384d56eec20a0414e24bae91b17d5f9e8f9b2f89d574a3f

gpu:
  nvidia:
    enabled: true
    runtimeClassName: nvidia

persistence:
  config:
    enabled: true
    size: 1Gi
    storageClass: synology-iscsi
  media:
    enabled: true
    size: 100Gi
    storageClass: nfs-slow

resources:
  limits:
    nvidia.com/gpu: 1

ingress:
  enabled: true
  annotations:
    ak-type: simple
    cert-manager.io/cluster-issuer: letsencrypt
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/name: Frigate
    gethomepage.dev/group: Smart Home
    gethomepage.dev/icon: frigate.png
  hosts:
  - host: frigate.k.oneill.net
    paths:
    - path: /
      portName: http
  tls:
  - secretName: frigate-tls
    hosts:
    - frigate.k.oneill.net
