# AUTO-GENERATED - DO NOT EDIT
# Generated by: scripts/gen-esphome-hosts
# Source: esphome/*.yaml configs
#
# To regenerate and apply: scripts/gen-esphome-hosts --apply

locals {
  esphome_hosts = {
    bedjet = {
      mac      = "24:0A:C4:C0:69:E8"
      ip       = "172.20.7.111"
      hostname = "bedjet.oneill.net"
      note     = "ESPHome: Bed Jet"
    }
    bedjet-power = {
      mac      = "C8:2B:96:06:40:6D"
      ip       = "172.20.7.189"
      hostname = "bedjet-power.oneill.net"
      note     = "ESPHome: BedJet Power"
    }
    freezer = {
      mac      = "EC:FA:BC:4F:E2:AA"
      ip       = "172.20.6.41"
      hostname = "freezer.oneill.net"
      note     = "ESPHome: Freezer"
    }
    freezer-door = {
      mac      = "4C:11:AE:0D:D9:E5"
      ip       = "172.20.7.156"
      hostname = "freezer-door.oneill.net"
      note     = "ESPHome: Freezer Door"
    }
    garage-bme280 = {
      mac      = "84:0D:8E:8F:4B:BE"
      ip       = "172.20.7.130"
      hostname = "garage-bme280.oneill.net"
      note     = "ESPHome: Garage BME280"
    }
    infra1-power = {
      mac      = "C4:5B:BE:E4:AB:22"
      ip       = "172.20.5.218"
      hostname = "infra1-power.oneill.net"
      note     = "ESPHome: Infra1"
    }
    living-room-bme280 = {
      mac      = "4C:11:AE:0D:D1:8A"
      ip       = "172.20.6.176"
      hostname = "living-room-bme280.oneill.net"
      note     = "ESPHome: Living Room BME280"
    }
    office-bme280 = {
      mac      = "4C:11:AE:0D:CD:08"
      ip       = "172.20.7.221"
      hostname = "office-bme280.oneill.net"
      note     = "ESPHome: Office BME280"
    }
    office-closet-lamp = {
      mac      = "A4:CF:12:B7:F7:D2"
      ip       = "172.20.5.137"
      hostname = "office-closet-lamp.oneill.net"
      note     = "ESPHome: Office Closet Lamp"
    }
    office-foot-warmer = {
      mac      = "B4:E6:2D:7F:A1:0C"
      ip       = "172.20.6.6"
      hostname = "office-foot-warmer.oneill.net"
      note     = "ESPHome: Office Foot Warmer"
    }
    office-heater = {
      mac      = "C4:5B:BE:E4:82:53"
      ip       = "172.20.6.149"
      hostname = "office-heater.oneill.net"
      note     = "ESPHome: Office Heater"
    }
    officedesk = {
      mac      = "CC:50:E3:C4:99:CD"
      ip       = "172.20.7.13"
      hostname = "officedesk.oneill.net"
      note     = "ESPHome: Office Desk"
    }
    opengarage-left-door = {
      mac      = "A4:CF:12:DE:93:EA"
      ip       = "172.20.4.97"
      hostname = "opengarage-left-door.oneill.net"
      note     = "ESPHome: OpenGarage Left Door"
    }
    opengarage-right-door = {
      mac      = "A4:CF:12:DE:9F:AC"
      ip       = "172.20.6.244"
      hostname = "opengarage-right-door.oneill.net"
      note     = "ESPHome: OpenGarage Right Door"
    }
    p1-power = {
      mac      = "48:3F:DA:2C:20:18"
      ip       = "172.20.6.148"
      hostname = "p1-power.oneill.net"
      note     = "ESPHome: P1"
    }
    p2-power = {
      mac      = "48:3F:DA:2B:FB:35"
      ip       = "172.20.7.163"
      hostname = "p2-power.oneill.net"
      note     = "ESPHome: P2"
    }
    p3-power = {
      mac      = "48:3F:DA:2B:78:8A"
      ip       = "172.20.5.22"
      hostname = "p3-power.oneill.net"
      note     = "ESPHome: P3"
    }
    p4-power = {
      mac      = "C8:2B:96:06:7A:88"
      ip       = "172.20.5.17"
      hostname = "p4-power.oneill.net"
      note     = "ESPHome: P4"
    }
    szamar-power = {
      mac      = "C4:5B:BE:E5:1F:43"
      ip       = "172.20.6.52"
      hostname = "szamar-power.oneill.net"
      note     = "ESPHome: Szamar Power"
    }
    temp-probe1 = {
      mac      = "4C:11:AE:0D:D3:27"
      ip       = "172.20.7.109"
      hostname = "temp-probe1.oneill.net"
      note     = "ESPHome: K-Type Thermocouple 1"
    }
    temp-probe2 = {
      mac      = "D8:F1:5B:14:71:13"
      ip       = "172.20.5.133"
      hostname = "temp-probe2.oneill.net"
      note     = "ESPHome: K-Type Thermocouple 2"
    }
    ups-power = {
      mac      = "48:3F:DA:2A:F4:96"
      ip       = "172.20.7.182"
      hostname = "ups-power.oneill.net"
      note     = "ESPHome: UPS Power"
    }
    x1c-ams1-monitor = {
      mac      = "A8:42:E3:47:6F:3C"
      ip       = "172.20.5.217"
      hostname = "x1c-ams1-monitor.oneill.net"
      note     = "ESPHome: X1C AMS1 Monitor"
    }
    x1c-ams2-monitor = {
      mac      = "A8:42:E3:46:F2:F8"
      ip       = "172.20.5.59"
      hostname = "x1c-ams2-monitor.oneill.net"
      note     = "ESPHome: X1C AMS2 Monitor"
    }
  }
}
