---
storageClass:
  create: false

volumeSnapshotClass:
  create: false

externalSnapshotter:
  enabled: false
  customResourceDefinitions:
    enabled: false

controller:
  defaultOnDeletePolicy: retain

feature:
  enableFSGroupPolicy: true
