---
# renovate: datasource=docker
zigbee2mqtt_image: "koenkk/zigbee2mqtt:2.12.1@sha256:80f7f04f72a99e4c4ef51ef7e98ee736edba6db0ecbb7abc626d0c4b0f1871f1"
zigbee2mqtt_data_dir: /etc/zigbee2mqtt
zigbee2mqtt_device: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_621e38fda096ed118be4c498a7669f5d-if00-port0
zigbee2mqtt_hostname: zigbee2mqtt.oneill.net
