---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: qbittorrent

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: api-key
    remoteRef:
      key: qbittorrent
      property: qbittorrent-api-key
  - secretKey: cross-seed-api-key
    remoteRef:
      key: qbittorrent
      property: cross-seed-api-key
