---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonAnnotations:
  argoManaged: 'true'

resources:
- deploy.yaml
- externalsecret.yaml
- pvc.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: qbittorrent-scripts
  files:
  - scripts/check-health.sh

generatorOptions:
  disableNameSuffixHash: true

labels:

- pairs:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
  includeSelectors: true
