---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: audiobookshelf

commonAnnotations:
  argoManaged: 'true'

components:
- ../components/authentik

resources:
- namespace.yaml
- externalsecret-oidc.yaml
- pvc-config.yaml
- pvc-metadata.yaml
- deploy.yaml
- service.yaml
- ingress.yaml
