---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: minuspod-env

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  target:
    name: minuspod-env
    creationPolicy: Owner
  dataFrom:
  - rewrite:
    - regexp:
        source: password
        target: MINUSPOD_MASTER_PASSPHRASE
    sourceRef:
      generatorRef:
        kind: Password
        name: minuspod-master-passphrase

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: minuspod-openrouter-env

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: minuspod-openrouter-env
    creationPolicy: Owner
  data:
  - secretKey: OPENROUTER_API_KEY
    remoteRef:
      key: minuspod-openrouter-api-key
