---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minuspod

resources:
- namespace.yaml
- password-generators.yaml
- externalsecret.yaml
- pvc.yaml
- deploy.yaml
- service.yaml
- ingress.yaml

components:
- ../components/authentik

commonAnnotations:
  argoManaged: 'true'

labels:

- pairs:
    app.kubernetes.io/name: minuspod
    app.kubernetes.io/instance: minuspod
  includeSelectors: true
