---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: cloudflared

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: TUNNEL_TOKEN
    remoteRef:
      key: cloudflare-tunnel
      property: TUNNEL_TOKEN
