---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: komga-oidc
  namespace: komga

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: komga-oidc
      property: client-id
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: komga-oidc
      property: client-secret
  target:
    name: komga-oidc
