---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: healthchecks

spec:
  refreshInterval: 24h
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: healthchecks
    creationPolicy: Owner
  data:
  - secretKey: HEALTHCHECK_PING_KEY
    remoteRef:
      key: healthchecks
      property: PING_KEY
