---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cpap-ezshare-sync

resources:
- namespace.yaml
- pvc.yaml
- cronjob.yaml

commonAnnotations:
  argoManaged: 'true'

labels:

- pairs:
    app.kubernetes.io/name: ezshare-sync
    app.kubernetes.io/instance: ezshare-sync
  includeSelectors: true

configMapGenerator:
- name: run-script
  files:
  - run
