---
apiVersion: batch/v1
kind: CronJob

metadata:
  name: vrroom-daily-reboot

spec:
  schedule: 0 5 * * *  # 5:00 AM daily in local time
  timeZone: America/New_York
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vrroom-daily-reboot
            image: alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40
            command: [/bin/sh, -c, echo "set reboot" | nc vrroom-37.oneill.net 2222]
          restartPolicy: Never
