---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: resticprofile-cache
  labels:
    app.kubernetes.io/instance: restic
    app.kubernetes.io/name: resticprofile
    app.kubernetes.io/component: cache

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
