---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: shelfmark-comics-oidc
  namespace: shelfmark-comics

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: shelfmark-comics-oidc
      property: client-id
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: shelfmark-comics-oidc
      property: client-secret
  target:
    name: shelfmark-comics-oidc
