---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shelfmark-comics

commonAnnotations:
  argoManaged: 'true'

resources:
- namespace.yaml
- externalsecret-oidc.yaml
- pvc-config.yaml
- deploy.yaml
- service.yaml
- ingress.yaml
