---
# Source: home-assistant/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hass-home-assistant
  namespace: hass
  labels:
    app.kubernetes.io/instance: hass
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/version: 2026.3.3
