---
substitutions:
  devicename: eightsleep-power
  device_id: eightsleep_power
  human_devicename: Eight Sleep Power
  icon: mdi:power-socket-us
  mac: C8:2B:96:06:40:6D
  ip: 172.20.7.189

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/sonoff_s31.yaml
