---
substitutions:
  devicename: temp-probe2
  device_id: temp_probe2
  human_devicename: K-Type Thermocouple 2
  icon: mdi:temperature
  mac: AC:A7:04:00:2F:94
  ip: 172.20.4.113

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  device_class: !include common/device-classes/m5stack_atoms3lite_kmeteriso.yaml
