---
schema: 1

warnings:
  basement-clock.yaml: []
  eightsleep-power.yaml: []
  freezer-door.yaml: []
  freezer.yaml: []
  garage-bme280.yaml: []
  infra1-power.yaml: []
  k3-power.yaml: []
  k4-power.yaml: []
  k5-power.yaml: []
  living-room-bme280.yaml: []
  office-bme280.yaml: []
  office-closet-lamp.yaml: []
  office-foot-warmer.yaml: []
  office-heater.yaml: []
  officedesk.yaml: []
  opengarage-left-door.yaml: []
  opengarage-right-door.yaml: []
  p1-power.yaml: []
  szamar-power.yaml: []
  temp-probe1.yaml:
  - GPIO35 is used by the PSRAM interface on ESP32-S3R8 / ESP32-S3R8V and should be
    avoided on these models
  temp-probe2.yaml:
  - GPIO35 is used by the PSRAM interface on ESP32-S3R8 / ESP32-S3R8V and should be
    avoided on these models
  temp-probe3.yaml: []
  ups-power.yaml: []
  x1c-ams1-monitor.yaml: []
  x1c-ams2-monitor.yaml: []
