#!/bin/bash

set -eu -o pipefail

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASEDIR"

source "$BASEDIR/../scripts/chart-version"

rm -rf helm tmp
mkdir tmp helm

helm_template nvidia-device-plugin nvidia-device-plugin \
	--values values.yaml \
	--namespace nvidia-device-plugin \
	--output-dir tmp

mv tmp/nvidia-device-plugin/templates/* helm
rm -rf tmp
