---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: whisperx-secrets

spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: whisperx-secrets
    creationPolicy: Owner
  data:
  - secretKey: HF_TOKEN
    remoteRef:
      key: hugging-face-readonly
      property: credential
