---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: whisperx-cache

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # Stores large-v3 and the pyannote diarization models.
      storage: 10Gi
