---
apiVersion: v1
kind: Service

metadata:
  name: whisperx

spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: whisperx
    app.kubernetes.io/instance: whisperx
