---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: unpoller
  labels:
    app: unpoller

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: unpoller
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: unifipoller
