#!/bin/bash

set -eu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASEDIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$(dirname "$BASEDIR")")"
cd "$SCRIPT_DIR"

# shellcheck source=../../../scripts/require-secrets
source "$REPO_ROOT/scripts/require-secrets"

image=$(yq -r .spec.jobTemplate.spec.template.spec.containers[0].image <"$BASEDIR/cronjobs/cronjob-b2.yaml")

mkdir -p .cache
mkdir -p .tmp
uuidgen >.tmp/uuid

require_secrets RESTIC_PASSWORD RCLONE_CONFIG_B2_ACCOUNT RCLONE_CONFIG_B2_KEY \
	RCLONE_CONFIG_B2C_PASSWORD RCLONE_CONFIG_B2C_PASSWORD2 || exit 1

# Now run the Docker container with the config file and necessary environment variables
docker run --rm \
	-e RESTIC_PASSWORD="$RESTIC_PASSWORD" \
	-e RESTIC_PASSWORD2="$RESTIC_PASSWORD" \
	-e RESTIC_FROM_PASSWORD="$RESTIC_PASSWORD" \
	-e RCLONE_RC_NO_AUTH=true \
	-e RCLONE_CONFIG_B2_ACCOUNT \
	-e RCLONE_CONFIG_B2_KEY \
	-e RCLONE_CONFIG_B2C_PASSWORD \
	-e RCLONE_CONFIG_B2C_PASSWORD2 \
	-v "$SCRIPT_DIR/.cache:/cache" \
	-v "$SCRIPT_DIR/.tmp:/tmp" \
	-v "$BASEDIR/profiles.yaml:/resticprofile-config/profiles.yaml:ro" \
	-v "$BASEDIR/rclone.conf:/rclone-config/rclone.conf:ro" \
	"$image" \
	-c /resticprofile-config/profiles.yaml \
	--lock-wait 6h \
	"$@"
