#!/bin/bash

set -eu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASEDIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$(dirname "$BASEDIR")")"
cd "$SCRIPT_DIR"

# shellcheck source=../../../scripts/require-secrets
source "$REPO_ROOT/scripts/require-secrets"

base_image=$(yq -r .spec.jobTemplate.spec.template.spec.containers[0].image <"$BASEDIR/cronjobs/cronjob-hetzner.yaml")
image_tag=$(yq -r ".images[] | select(.name == \"$base_image\") | .newTag" <"$BASEDIR/kustomization.yaml")

if [[ "$image_tag" == "null" || -z "$image_tag" ]]; then
	image="$base_image"
else
	image="${base_image}:$image_tag"
fi

mkdir -p .cache
mkdir -p .tmp
uuidgen >.tmp/uuid

require_secrets RESTIC_PASSWORD \
	RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_URL RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_USER RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_PASS \
	RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_URL RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_USER RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_PASS \
	RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_URL RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_USER RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_PASS \
	RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_MAIN_PASSWORD \
	RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_MAIN_PASSWORD2 \
	RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_XTAL_PASSWORD \
	RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_XTAL_PASSWORD2 || exit 1

for env_name in \
	RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_PASS \
	RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_PASS \
	RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_PASS; do
	printf -v "$env_name" '%s' "$(rclone obscure "${!env_name}")"
	export "${env_name?}"
done

# Now run the Docker container with the config file and necessary environment variables
docker run --rm \
	-e RESTIC_PASSWORD="$RESTIC_PASSWORD" \
	-e RESTIC_PASSWORD2="$RESTIC_PASSWORD" \
	-e RESTIC_FROM_PASSWORD="$RESTIC_PASSWORD" \
	-e RCLONE_RC_NO_AUTH=true \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_URL \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_USER \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_PASS \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_URL \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_USER \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_PASS \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_URL \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_USER \
	-e RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_PASS \
	-e RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_MAIN_PASSWORD \
	-e RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_MAIN_PASSWORD2 \
	-e RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_XTAL_PASSWORD \
	-e RCLONE_CONFIG_HETZNER_CRYPT_RESTIC_XTAL_PASSWORD2 \
	-v "$SCRIPT_DIR/.cache:/cache" \
	-v "$SCRIPT_DIR/.tmp:/tmp" \
	-v "$BASEDIR/profiles.yaml:/resticprofile-config/profiles.yaml:ro" \
	-v "$BASEDIR/rclone.conf:/rclone-config/rclone.conf:ro" \
	"$image" \
	-c /resticprofile-config/profiles.yaml \
	--lock-wait 6h \
	"$@"
