#!/usr/bin/env bash
set -eo pipefail

# Script to run rclone with secrets from 1Password
# For local development use only

# Directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
BASEDIR="$(dirname "$SCRIPT_DIR")"
TEMP_RCLONE_CONFIG="/tmp/rclone.conf"

source "$SCRIPT_DIR/get-1password-secrets"

# Running locally, fetch secrets from 1Password
echo "Fetching secrets from 1Password"

# Get all rclone environment variables
export_rclone_env_variables

# Create a temporary rclone config
cp "$BASEDIR/rclone.conf" "$TEMP_RCLONE_CONFIG"

# Set the config file location
export RCLONE_CONFIG="$TEMP_RCLONE_CONFIG"

# Run the actual rclone command with all arguments passed to this script
echo "Running rclone with secure configuration"
exec rclone "$@"
