---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restic

resources:
- shared
- rest-server
- cronjobs

commonAnnotations:
  argoManaged: 'true'

configMapGenerator:
- files:
  - profiles.yaml
  - body-start.txt
  - body-success.txt
  - body-failure.txt
  name: resticprofile-config
  options:
    disableNameSuffixHash: true
- files:
  - rclone.conf
  name: rclone-config
  options:
    disableNameSuffixHash: true

images:
- name: creativeprojects/resticprofile
  newTag: 0.32.0@sha256:b672ab22f452518bd7f11c2b0a9ca48547b5d2935f80cc3dc1dadf66c784f543

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: restic
    app.kubernetes.io/instance: restic
