---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restic

resources:
- shared
- rest-server
- cronjobs

commonAnnotations:
  argoManaged: 'true'

configMapGenerator:
- files:
  - profiles.yaml
  - body-start.txt
  - body-success.txt
  - body-failure.txt
  name: resticprofile-config
  options:
    disableNameSuffixHash: true
- files:
  - rclone.conf
  name: rclone-config
  options:
    disableNameSuffixHash: true

images:
- name: creativeprojects/resticprofile
  newTag: 0.32.0@sha256:2d1ff9a32ec23cb231fba7abecc5a014cb1fa44cc1d7100327cceed92481a4c7

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: restic
    app.kubernetes.io/instance: restic
