---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restic

resources:
- shared
- rest-server
- cronjobs

commonAnnotations:
  argoManaged: 'true'

configMapGenerator:
- files:
  - profiles.yaml
  - body-start.txt
  - body-success.txt
  - body-failure.txt
  name: resticprofile-config
  options:
    disableNameSuffixHash: true
- files:
  - rclone.conf
  name: rclone-config
  options:
    disableNameSuffixHash: true

images:
- name: creativeprojects/resticprofile
  newTag: 0.32.0@sha256:81069ba7e40d461e311a02e870f513cebf9f36eef653893b816af86c3e33ffc9

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: restic
    app.kubernetes.io/instance: restic
