[b2]
type = b2
account = ${RCLONE_CONFIG_B2_ACCOUNT}
key = ${RCLONE_CONFIG_B2_KEY}
hard_delete = true

[b2c]
type = crypt
remote = b2:cmo-restic
filename_encryption = standard
directory_name_encryption = true
# password and password2 will come from environment variables

[hetzner_webdav_restic_main]
type = webdav
url = ${RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_URL}
vendor = other
user = ${RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_MAIN_USER}
# pass will come from environment variables

[hetzner_webdav_restic_xtal]
type = webdav
url = ${RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_URL}
vendor = other
user = ${RCLONE_CONFIG_HETZNER_WEBDAV_RESTIC_XTAL_USER}
# pass will come from environment variables

[hetzner_webdav_root]
type = webdav
url = ${RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_URL}
vendor = other
user = ${RCLONE_CONFIG_HETZNER_WEBDAV_ROOT_USER}
# pass will come from environment variables

[hetzner_crypt_restic_main]
type = crypt
remote = hetzner_webdav_restic_main:
filename_encryption = standard
directory_name_encryption = true
# password and password2 will come from environment variables

[hetzner_crypt_restic_xtal]
type = crypt
remote = hetzner_webdav_restic_xtal:
filename_encryption = standard
directory_name_encryption = true
# password and password2 will come from environment variables
