---
name: Terraform checks

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    name: Terraform checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
      with:
        persist-credentials: false

    - name: Check for Terraform-related changes
      if: env.ACT != 'true'
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706  # v4
      id: changes
      with:
        filters: |
          terraform:
            - 'opentofu/**'
            - 'flake.nix'
            - 'flake.lock'
            - '.pre-commit-config.yaml'
            - '.github/workflows/terraform.yaml'

    - name: Install Nix
      if: env.ACT != 'true' && steps.changes.outputs.terraform == 'true'
      uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342  # v31
      with:
        github_access_token: ${{ github.token }}

    - name: Setup Cachix
      if: env.ACT != 'true' && steps.changes.outputs.terraform == 'true'
      uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71  # v17
      with:
        name: claytono
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Cache pre-commit
      if: env.ACT != 'true' && steps.changes.outputs.terraform == 'true'
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25  # v5
      with:
        path: ~/.cache/pre-commit
        key: precommit-terraform-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          precommit-terraform-
          precommit-

    - name: Run terraform checks
      if: steps.changes.outputs.terraform == 'true' || env.ACT == 'true'
      run: |-
        nix develop --extra-experimental-features 'nix-command flakes' --option sandbox false --command pre-commit run terraform_validate
        nix develop --extra-experimental-features 'nix-command flakes' --option sandbox false --command pre-commit run terraform_providers_lock
